<?php
/**
 * @author <marcin.kurczewski@gammanet.pl> Marcin Kurczewski
 */
if (isset($this->response))
{
	if (isset($this->response['outputJSON']['message']))
	{
		echo '<p class="notice error">Błąd: ' . $this->response['outputJSON']['message'] . '</p>';
	}
	elseif (($this->response['outputStatusCode'] == 200) or isset($this->response['outputJSON']['id']))
	{
		header('Location: ' . $this->url(array('controller' => 'grades', 'action' => 'index'), null, false));
		echo '<p class="notice">Lekcja edytowana z sukcesem.</p>';
	}
	else
	{
		echo '<p class="notice error">Wystąpiły błędy podczas próby edycji lekcji.</p>';
	}
}
else
{
?>
<div class="op shaded">
	<ul class="op">
		<li class="icon-return"><a class="action-cancel action-return" href="<?php echo $this->url(array('controller' => 'grades', 'action' => 'index'), null, false); ?>">Powrót</a></li>
	</ul>
</div>

<form id="grades-create-exam-form" action="<?php echo $this->url(array('controller' => 'grades', 'action' => 'create-exam', 'id' => $this->record['outputJSON']['id']), null, false); ?>" method="post">
	<fieldset>
		<legend>Nowa ocena</legend>
		<div>
			<label>Użytkownik</label>
			<input disabled="disabled" value="<?php echo $this->grades['outputJSON']['users'][$this->userId]; ?>">
		</div>
		<div>
			<label for="edit-name">Kategoria oceny</label>
			<input class="required name" id="edit-name" name="name" placeholder="Kartkówka, sprawdzian...">
		</div>
		<div>
			<label for="edit-date">Data</label>
			<input class="required date" id="edit-date" name="date" value="<?php echo date('d-m-Y'); ?>">
		</div>
		<div>
			<label for="edit-grade">Ocena</label>
			<select class="required" id="edit-grade" name="grade">
			<?php
				$grades = array
				(
					array('title' => 'brak oceny', 'value' => 0),
					array('title' => '1',  'value' => 1),
					array('title' => '1+', 'value' => 1.5),
					array('title' => '2-', 'value' => 1.75),
					array('title' => '2',  'value' => 2),
					array('title' => '2+', 'value' => 2.5),
					array('title' => '3-', 'value' => 2.75),
					array('title' => '3',  'value' => 3),
					array('title' => '3+', 'value' => 3.5),
					array('title' => '4-', 'value' => 3.75),
					array('title' => '4',  'value' => 4),
					array('title' => '4+', 'value' => 4.5),
					array('title' => '5-', 'value' => 4.75),
					array('title' => '5',  'value' => 5),
					array('title' => '5+', 'value' => 5.5),
					array('title' => '6-', 'value' => 5.75),
					array('title' => '6',  'value' => 6),
				);
				foreach ($grades as $index => $grade)
				{
					$sel = $index == 0;
					echo '<option value="' . $grade['value'] . '"' . ($sel ? ' selected="selected"' : '') . '>' . $grade['title'] . '</option>';
				}
			?>
			</select>
		</div>
	</fieldset>
	<div class="op">
		<button class="button default action-add" name="submit-action" type="submit" value="create">Utwórz</button>
		<button class="button action-cancel" name="submit-action" type="button" value="cancel" onclick="window.location.href='<?php echo $this->url(array('controller' => 'grades', 'action' => 'index'), null, false); ?>'; return false; ">Anuluj</button>
	</div>
	<input type="hidden" id="edit-name-source" name="type-source" value="<?php
		$out = array();
		if (isset($this->grades['outputJSON']['exams']))
		{
			foreach ($this->grades['outputJSON']['exams'] as $examId => $exam)
			{
				$out []= $exam['name'];
			}
		}
		echo htmlspecialchars(json_encode(array_unique($out)));
		?>">
</table>
</form>
<?php
}
?>
