<?
global $SERVER_ID,$lang,$ver,$adodb,$DEFAULT_PATH_PAGES,$sitemap;

push($adodb);
$adodb=$kameleon_adodb;

//=======================================================================================
$sitemap[SERVER_ID][]	= array(SERVER_ID=>11,SITE=>'www.fakro.ru',lang=>'ru');
$sitemap[SERVER_ID][]	= array(SERVER_ID=>14,SITE=>'www.fakro.de',lang=>'de');
$sitemap[SERVER_ID][]	= array(SERVER_ID=>12,SITE=>'www.fakro.nl',lang=>'nl');
$sitemap[SERVER_ID][]	= array(SERVER_ID=>13,SITE=>'www.fakro.fr',lang=>'fr');
$sitemap[SERVER_ID][]	= array(SERVER_ID=>29,SITE=>'www.fakro.hu',lang=>'hu');
$sitemap[SERVER_ID][]	= array(SERVER_ID=>35,SITE=>'www.7dolin.pl',lang=>'i');
$sitemap[SERVER_ID][]	= array(SERVER_ID=>19,SITE=>'www.fakro.com',lang=>'e');
$sitemap[SERVER_ID][]	= array(SERVER_ID=>5,SITE=>'www.fakro.pl',lang=>'i');
$sitemap[SERVER_ID][]	= array(SERVER_ID=>50,SITE=>'www.fakro.co.uk',lang=>'e');
$sitemap[SERVER_ID][]	= array(SERVER_ID=>49,SITE=>'www.fakro.ua',lang=>'ua');
$sitemap[SERVER_ID][]	= array(SERVER_ID=>44,SITE=>'www.fakro.sk',lang=>'sk');
$sitemap[SERVER_ID][]	= array(SERVER_ID=>45,SITE=>'www.fakrousa.com',lang=>'e');
$sitemap[SERVER_ID][]	= array(SERVER_ID=>46,SITE=>'www.fakro.cz',lang=>'cz');
$sitemap[SERVER_ID][]	= array(SERVER_ID=>41,SITE=>'sklep.fakro.fr',lang=>'fr');
$sitemap[SERVER_ID][]	= array(SERVER_ID=>4,SITE=>'sklep.fakro.pl',lang=>'i');
$sitemap[SERVER_ID][]	= array(SERVER_ID=>40,SITE=>'sklep.fakro.de',lang=>'de');
$sitemap[SERVER_ID][]	= array(SERVER_ID=>42,SITE=>'sklep.fakro.nl',lang=>'nl');
$sitemap[SERVER_ID][]	= array(SERVER_ID=>43,SITE=>'sklep.fakro.ru',lang=>'ru');
//=======================================================================================

function sitemap($INCLUDE_PATH,$sitemap) {
	global $SERVER_ID,$lang,$ver,$adodb,$DEFAULT_PATH_PAGES,$sitemap;
	
	foreach($sitemap[SERVER_ID] as $key => $value) {
		if($sitemap[select] == $sitemap[SERVER_ID][$key][SERVER_ID]) {
			$SERVER_ID	= $sitemap[SERVER_ID][$key][SERVER_ID];
			$lang		= $sitemap[SERVER_ID][$key][lang];
			$ver		= 1;
			$SITE		= $sitemap[SERVER_ID][$key][SITE];
			}
		}
	
	$sql = "SELECT id,file_name,nd_ftp FROM webpage WHERE (nositemap!=1 OR nositemap IS NULL) AND server=".$SERVER_ID." AND lang='".$lang."' AND ver=".$ver." ORDER BY id,title";
	$res = $adodb->execute($sql);
	
	$sitemap = "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n";
	$sitemap .= "<?xml-stylesheet type=\"text/xsl\" href=\"gss.xsl\"?>\n";
	$sitemap .= "<urlset xmlns=\"http://www.google.com/schemas/sitemap/0.84\" xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\" xsi:schemaLocation=\"http://www.google.com/schemas/sitemap/0.84 http://www.google.com/schemas/sitemap/0.84/sitemap.xsd\">\n";
	$sitemap .= "<!--#Generated by SOFTplus GSiteCrawler v1.12 rev. 260 by SOFTplus Entwicklungen GmbH, http://johannesmueller.com/gs/, http://www.softplus.net/ -->\n";
	
	for($i=0; $i < $res->RecordCount(); $i++) {
		parse_str(ado_explodename($res,$i));
		
		$sitemap .= '<url>';
		$sitemap .= '<loc>http://'.$SITE.'/';
		
		if($file_name) {
			$sitemap .= $file_name;
			}else{
			$sitemap .= 'html'.$lang.'/'.$id.'.php';
			}
		$sitemap .= '</loc>';
		$sitemap .= '<lastmod>'.date("Y-m-d",$nd_ftp).'T'.date("H:m:s",$nd_ftp).'+00:00</lastmod>';
		$sitemap .= '<changefreq>daily</changefreq>';
		$sitemap .= '<priority>0.50</priority>';
		$sitemap .= '</url>';
		$sitemap .= "\n";
		}
	
	$sitemap .= "</urlset>";
	
	$p=fopen($INCLUDE_PATH."/google_sitemap/sitemap.xml",'w');
	fwrite($p,$sitemap);
	fclose($p);
	
	echo 'pliki do pobrania: ';
	echo '<a href="'.$INCLUDE_PATH.'/google_sitemap/sitemap.xml" target="_blank">sitemap.xml</a> &nbsp;&nbsp; <a href="'.$INCLUDE_PATH.'/google_sitemap/gss.xsl" target="_blank">gss.xsl</a><br> (zapisz element docelowy jako...)';
	}
//------------------------------------------------------------------------

echo "
<fieldset style=\"width:99%; margin-left:2px;\">
<legend>Google Sitemap (FAKRO)</legend>";

echo "<div align=\"right\"><br><form method=post action=\"$self\">";
echo "<select name=\"sitemap[select]\">";

foreach($sitemap[SERVER_ID] as $key => $value)
	echo "<option value=\"".$sitemap[SERVER_ID][$key][SERVER_ID]."\" ".(($sitemap[select] == $sitemap[SERVER_ID][$key][SERVER_ID])?"selected":"").">".$sitemap[SERVER_ID][$key][SITE]."</option>";

echo "</select>";
echo "<INPUT TYPE=\"submit\" value=\"generuj\" class=\"k_button\"></div>";
echo "</form>";
echo "<br><br>";

if($sitemap[select]) {
	sitemap($INCLUDE_PATH,$sitemap[select]);
	}

echo "</fieldset>";
echo "<div align=\"right\">sid: ".$WEBTD->sid."</div>";
?>
