<div class="hidden" id="dialogBoxOverlay">

	<div class="hidden" id="preloader">
		<div><img src="<?php echo $this->baseUrl(); ?>/img/ajax-loader.gif" alt="Ajax loader" /></div>
	</div>

	<div class="hidden" id="confirm">
		<div>
			<h2><?php echo $this->translate('Czy jesteś pewien?'); ?></h2>
			<div class="clearfix">
				<div id="confirmYes"><?php echo $this->translate('tak'); ?></div>
				<div id="confirmNo"><?php echo $this->translate('nie'); ?></div>
			</div>
		</div>
	</div>

	<div class="hidden" id="confirmLifeBuoy">
		<div>
			<h2><?php echo $this->translate('Czy chcesz wykorzystać koło ratunkowe?'); ?></h2>
			<div class="clearfix">
				<div id="confirmLifeBuoyYes"><?php echo $this->translate('tak'); ?></div>
				<div id="confirmLifeBuoyNo"><?php echo $this->translate('nie'); ?></div>
			</div>
		</div>
	</div>

	<div class="dialogBoxWelcome hidden" id="welcome">
		<div>
			<h2><?php echo $this->translate('Witaj').' '.$this->gameData['nick']; ?>!</h2>
			<div class="content center">
				<p><?php echo $this->translate('Przygotuj się do gry! Kliknij "Start" aby rozpocząć.'); ?></p>
				<img src="<?php echo $this->baseUrl(); ?>/img/start.png" alt="<?php echo $this->translate('Start testu'); ?>" />
			</div>
		</div>
	</div>

	<div class="dialogBoxWelcome hidden" id="welcome_group">
		<div>
			<h2><?php echo $this->translate('Witajcie!'); ?>!</h2>
			<div class="content center">
				<p><?php echo $this->translate('Gdy zespół będzie gotowy do gry, kapitan klika "Start" aby rozpocząć.'); ?></p>
				<img src="<?php echo $this->baseUrl(); ?>/img/start.png" alt="<?php echo $this->translate('Dołącz'); ?>" />
			</div>
		</div>
	</div>

	<div class="dialogBoxWelcome hidden" id="welcome_group2">
		<div>
			<h2><?php echo $this->translate('Witajcie!'); ?>!</h2>
			<div class="content center">
				<p><?php echo $this->translate('Gdy zespół będzie gotowy do gry, kapitan klika "Start" aby rozpocząć.'); ?></p>
				<img src="<?php echo $this->baseUrl(); ?>/img/start.png" alt="<?php echo $this->translate('Dołącz'); ?>" />
			</div>
		</div>
	</div>

	<div class="dialogBoxWelcomeAnonymous hidden" id="welcome_anonymous">
		<div>
			<h2><?php echo $this->translate('Witaj').' '.$this->gameData['nick']; ?>!</h2>
			<div class="content center">
				<p><?php echo $this->translate('Czas na rozwiązanie testu to %s.','<strong id="welcomeTime"></strong>'); ?></p>
				<img src="<?php echo $this->baseUrl(); ?>/img/start.png" alt="<?php echo $this->translate('Start testu'); ?>" />
			</div>
		</div>
	</div>
	
	<div class="dialogBoxLifeBuoy hidden" id="box_lifeBuoys1">
		<div>
			<h2><?php echo $this->translate('Ekspert'); ?></h2>
			<div class="content"></div>
		</div>
	</div>
	
	<div class="dialogBoxLifeBuoy hidden" id="box_lifeBuoys2">
		<div>
			<h2><?php echo $this->translate('Badania'); ?></h2>
			<div class="content"></div>
		</div>
	</div>
	
	<div class="dialogBoxLifeBuoy hidden" id="box_lifeBuoys3">
		<div>
			<h2><?php echo $this->translate('50/50'); ?></h2>
			<div class="content"></div>
		</div>
	</div>
	
	<div class="dialogBox hidden" id="poprawna">
		<div>
			<h2><?php echo $this->translate('Odpowiedź prawidłowa!'); ?></h2>
			<div class="content center">
				<p><img src="<?php echo $this->baseUrl(); ?>/img/<?php echo $this->translate('btn_dalej.png'); ?>" alt="<?php echo $this->translate('Kliknij by przejść dalej.'); ?>" /></p>
				<?php if(isset($this->user->id)) { ?>
					<p class="aRight flagLink"><?php echo $this->translate('Zgłoś uwagi do tego pytania'); ?></p>
				<?php } ?>
			</div>
		</div>
	</div>
	
	<div class="flagBox hidden" id="flag">
		<div>
			<h2><?php echo $this->translate('Zgłoś uwagi do tego pytania'); ?></h2>
			<div class="content center">
				<div class="content center">
					<textarea rows="10" cols="30"></textarea>
					<input type="button" id="flagSend" value="<?php echo $this->translate('Wyślij'); ?>" />					
					<input type="button" id="flagCancel" value="<?php echo $this->translate('Anuluj'); ?>" />					
				</div>
			</div>
		</div>
	</div>

	<div class="dialogBox hidden" id="niePoprawna">
		<div>
			<h2><?php echo $this->translate('Odpowiedź nieprawidłowa!'); ?></h2>
			<div class="content center">
				<p><img src="<?php echo $this->baseUrl(); ?>/img/<?php echo $this->translate('btn_dalej.png'); ?>" alt="<?php echo $this->translate('Kliknij by przejść dalej.'); ?>" /></p>				
				<?php if(isset($this->user->id)) { ?>
					<p class="aRight flagLink"><?php echo $this->translate('Zgłoś uwagi do tego pytania'); ?></p>
				<?php } ?>
			</div>
		</div>
	</div>
	
	<div class="dialogBoxNewGame hidden" id="czasMinal">
		<div>
			<h2><?php echo $this->translate('Czas minął! Kliknij tutaj jeżeli chcesz zacząć jeszcze raz!'); ?></h2>
			<br />			
			<div class="content"><?php echo $this->translate('Twój wynik to:'); ?> <span class="koniecGryPunkty">0</span> <?php echo $this->translate('punktów'); ?>. <span class="lifeBuoysPointsBlock hidden"><?php echo $this->translate('W tym <span class="lifeBuoysPoints"></span> za niewykorzystane koła ratunkowe.'); ?></span></div>
			<p><img src="<?php echo $this->baseUrl(); ?>/img/<?php echo $this->translate('btn_koniec.png'); ?>" alt="<?php echo $this->translate('Koniec gry.'); ?>" style="margin: 15px 0 0 0;" /></p>				
			<?php if(isset($this->user->id)) { ?>
				<p class="aRight flagLink"><?php echo $this->translate('Zgłoś uwagi do tego pytania'); ?></p>
			<?php } ?>
			<?php if(isset($this->gameData['modePlayers'])&&$this->gameData['modePlayers']==2) { ?>
				<p class="aRight stayLink"><?php echo $this->translate('Pozostań i obserwuj grę rywali'); ?></p>
			<?php } ?>
		</div>
	</div>

	<div class="dialogBoxNewGame hidden" id="koniecPytan">
		<div>
			<h2><?php echo $this->translate('Odpowiedziałeś na wszystkie pytania!'); ?></h2>
			<div class="content"><?php echo $this->translate('Twój wynik to:'); ?> <span class="koniecGryPunkty">0</span> <?php echo $this->translate('punktów'); ?>. <span class="lifeBuoysPointsBlock hidden"><?php echo $this->translate('W tym <span class="lifeBuoysPoints"></span> za niewykorzystane koła ratunkowe.'); ?></span></div>
			<?php if(isset($this->user->id)) { ?>
				<p class="aRight flagLink"><?php echo $this->translate('Zgłoś uwagi do tego pytania'); ?></p>
			<?php } ?>
			<?php if(isset($this->gameData['modePlayers'])&&$this->gameData['modePlayers']==2) { ?>
				<p class="aRight stayLink"><?php echo $this->translate('Pozostań i obserwuj grę rywali'); ?></p>
			<?php } ?>
		</div>
	</div>

	<div class="dialogBoxNewGame hidden" id="koniecGry">
		<div>
			<h2><?php echo $this->translate('Odpowiedź nieprawidłowa!%sKoniec gry!','<br/>'); ?></h2>
			<div class="content"><?php echo $this->translate('Twój wynik to:'); ?> <span class="koniecGryPunkty">0</span> <?php echo $this->translate('punktów'); ?>. <span class="lifeBuoysPointsBlock hidden"><?php echo $this->translate('W tym <span class="lifeBuoysPoints"></span> za niewykorzystane koła ratunkowe.'); ?></span></div>
			<p><img src="<?php echo $this->baseUrl(); ?>/img/<?php echo $this->translate('btn_koniec.png'); ?>" alt="<?php echo $this->translate('Koniec gry.'); ?>" style="margin: 15px 0 0 0;" /></p>
			<?php if(isset($this->user->id)) { ?>
				<p class="aRight flagLink"><?php echo $this->translate('Zgłoś uwagi do tego pytania'); ?></p>
			<?php } ?>
			<?php if(isset($this->gameData['modePlayers'])&&$this->gameData['modePlayers']==2) { ?>
				<p class="aRight stayLink"><?php echo $this->translate('Pozostań i obserwuj grę rywali'); ?></p>
			<?php } ?>
		</div>
	</div>

	<div class="dialogBoxNewGame hidden" id="koniecGryPoprawna">
		<div>
			<h2><?php echo $this->translate('Odpowiedź prawidłowa!'); ?></h2>
			<div class="content center">
				<br />
				<p><?php echo $this->translate('Koniec gry!%sOdpowiedziałeś już na wszystkie pytania!','<br/>'); ?></p>
				<p><?php echo $this->translate('Twój wynik to:'); ?> <span class="koniecGryPunkty">0</span> <?php echo $this->translate('punktów'); ?>. <span class="lifeBuoysPointsBlock hidden"><?php echo $this->translate('W tym <span class="lifeBuoysPoints"></span> za niewykorzystane koła ratunkowe.'); ?></span></p>
				<p><img src="<?php echo $this->baseUrl(); ?>/img/<?php echo $this->translate('btn_dalej.png'); ?>" alt="<?php echo $this->translate('Kliknij by przejść dalej.'); ?>" /></p>				
				<?php if(isset($this->user->id)) { ?>
					<p class="aRight flagLink"><?php echo $this->translate('Zgłoś uwagi do tego pytania'); ?></p>
				<?php } ?>
				<?php if(isset($this->gameData['modePlayers'])&&$this->gameData['modePlayers']==2) { ?>
					<p class="aRight stayLink"><?php echo $this->translate('Pozostań i obserwuj grę rywali'); ?></p>
				<?php } ?>
			</div>
		</div>
	</div>
	
	<div class="dialogBoxNewGame hidden" id="koniecGryFull">
		<div>
			<h2><?php echo $this->translate('Koniec gry!%sOdpowiedziałeś już na wszystkie pytania!','<br/>'); ?></h2>
			<br />
			<div class="content"><?php echo $this->translate('Twój wynik to:'); ?> <span class="koniecGryPunkty">0</span> <?php echo $this->translate('punktów'); ?>. <span class="lifeBuoysPointsBlock hidden"><?php echo $this->translate('W tym <span class="lifeBuoysPoints"></span> za niewykorzystane koła ratunkowe.'); ?></span></div>
		</div>
	</div>
</div>
	<div id="pageWrapper">
		<div id="test">
			<div id="testTop">
				<a href="<?php echo $this->baseUrl(); ?>/gra/"><img src="<?php echo $this->baseUrl(); ?>/img/headmaster_logo.png" alt="<?php echo $this->translate('HeadMaster'); ?>" class="logo" width="287" height="48" /></a>
				<ul id="lifeBuoys">
					<li id="lifeBuoys1">
						<?php if(isset($this->gameData['lifeBuoys']['1'])) {
							$class = 'off';
						} else {
							$class = 'on';
						} ?>
						<a href="javascript: void(0);" class="<?php echo $class; ?>"><span><?php echo $this->translate('Ekspert'); ?></span></a>
					</li>
					<li id="lifeBuoys2">
						<?php if(isset($this->gameData['lifeBuoys']['2'])) {
							$class = 'off';
						} else {
							$class = 'on';
						} ?>
						<a href="javascript: void(0);" class="<?php echo $class; ?>"><span><?php echo $this->translate('Badanie opinii'); ?></span></a>
					</li>
					<li id="lifeBuoys3">
						<?php if(isset($this->gameData['lifeBuoys']['3'])) {
							$class = 'off';
						} else {
							$class = 'on';
						} ?>
						<a href="javascript: void(0);" class="<?php echo $class; ?>"><span><?php echo $this->translate('50/50'); ?></span></a>
					</li>
				</ul>
				<div id="testTimer">
					<img src="<?php echo $this->baseUrl(); ?>/img/zegar.png" alt="Zegar" class="fleft" />
					<h2><?php echo $this->translate('Pozostało'); ?>:&nbsp;<strong id="timeLeft"><?php echo floor($this->time/6000).'&nbsp;min'; ?></strong></h2>
					<div id="testProgress">
						<div class="progressBarOut">
							<div class="progressBar"></div>
						</div>
					</div>
				</div>
				<div id="soundSwitch"><div></div></div>
			</div>
			<div id="testContent" class="clearfix">
				<div id="testIlustracja">
					<?php
					if(isset($this->question->media)&&$this->question->media!=''&&strstr($this->question->media,'youtube')) {
						$media = parse_url($this->question->media);
						parse_str($media['query'], $yt);
					}
					if(isset($yt)) {
						echo '<div id="youtube_'.$this->question->id.'" class="youtube"><iframe width="560" height="348" src="http://www.youtube.com/embed/'.$yt['v'].'?wmode=transparent" frameborder="0" allowfullscreen></iframe></div>';
					} else {
						if(file_exists('uploads/'.$this->question->question_hash.'.jpg')) {
							echo '<a class="currentQuestion testIlustracjaBig" href="'.$this->baseUrl().'/uploads/'.$this->question->question_hash.'_big.jpg" rel="prettyPhoto"><img src="'.$this->baseUrl().'/uploads/'.$this->question->question_hash.'.jpg" alt="'.$this->question->question_hash.'" /></a><div id="magnify_glass"></div>';
						} else {
							echo '<a class="currentQuestion" href=""><img src="'.$this->baseUrl().'/img/questions/default/'.rand(0,38).'.jpg" alt="'.$this->question->question_hash.'" /></a>';
						}		   
					}
					?>
				</div>
				<div id="testText">
					<h2><?php echo $this->translate('Pytanie'); ?> <span><?php echo $this->gameData['step']+1; ?></span>:</h2>
					<p class="currentQuestion"><?php echo $this->question->question; ?></p>
					<p class="newQuestion hidden"></p>
				</div>
				<div id="testPoints">
					<h2><?php echo $this->translate('Ilość punktów'); ?></h2>
					<ul>
						<li>100</li>
						<li>90</li>
						<li>80</li>
						<li>70</li>
						<li>60</li>
						<li>50</li>
						<li>40</li>
						<li>30</li>
						<li>20</li>
						<li>10</li>
					</ul>
				</div>
				<ul id="testAnswers">
					<li class="fleft">
						<a href="javascript: void(0);" class="currentQuestion" name="<?php echo $this->answers[0]['id']; ?>" id="testAnswer1"><span><?php echo $this->answers[0]['answer']; ?></span></a>
						<a href="javascript: void(0);" class="newQuestion" style="display:none;"><span></span></a>							
					</li>
					<li class="fright">
						<a href="javascript: void(0);" class="currentQuestion" name="<?php echo $this->answers[1]['id']; ?>" id="testAnswer2"><span><?php echo $this->answers[1]['answer']; ?></span></a>
						<a href="javascript: void(0);" class="newQuestion" style="display:none;"><span></span></a>							
					</li>
					<li class="fleft">
						<a href="javascript: void(0);" class="currentQuestion" name="<?php echo $this->answers[2]['id']; ?>" id="testAnswer3"><span><?php echo $this->answers[2]['answer']; ?></span></a>
						<a href="javascript: void(0);" class="newQuestion" style="display:none;"><span></span></a>							
					</li>
					<li class="fright">
						<a href="javascript: void(0);" class="currentQuestion" name="<?php echo $this->answers[3]['id']; ?>" id="testAnswer4"><span><?php echo $this->answers[3]['answer']; ?></span></a>
						<a href="javascript: void(0);" class="newQuestion" style="display:none;"><span></span></a>							
					</li>
				</ul>
			</div>
 			<ul id="groupMode" class="hidden">
				<li class="groupModeItem" id="groupModeItem_1">
					<ul class="points">
						<li></li>
						<li></li>
						<li></li>
						<li></li>
						<li></li>
						<li></li>
						<li></li>
						<li></li>
						<li></li>
						<li></li>
					</ul>
					<h2></h2>
					<p></p>
					<ul class="lifeBuoys">
						<li class="lifeBuoy1"></li>
						<li class="lifeBuoy2"></li>
						<li class="lifeBuoy3"></li>
					</ul>
				</li>
				<li class="groupModeItem" id="groupModeItem_2">
					<ul class="points">
						<li></li>
						<li></li>
						<li></li>
						<li></li>
						<li></li>
						<li></li>
						<li></li>
						<li></li>
						<li></li>
						<li></li>
					</ul>
					<h2></h2>
					<p></p>
					<ul class="lifeBuoys">
						<li class="lifeBuoy1"></li>
						<li class="lifeBuoy2"></li>
						<li class="lifeBuoy3"></li>
					</ul>
				</li>
				<li class="groupModeItem" id="groupModeItem_3">
					<ul class="points">
						<li></li>
						<li></li>
						<li></li>
						<li></li>
						<li></li>
						<li></li>
						<li></li>
						<li></li>
						<li></li>
						<li></li>
					</ul>
					<h2></h2>
					<p></p>
					<ul class="lifeBuoys">
						<li class="lifeBuoy1"></li>
						<li class="lifeBuoy2"></li>
						<li class="lifeBuoy3"></li>
					</ul>
				</li>
				<li class="groupModeItem" id="groupModeItem_4">
					<ul class="points">
						<li></li>
						<li></li>
						<li></li>
						<li></li>
						<li></li>
						<li></li>
						<li></li>
						<li></li>
						<li></li>
						<li></li>
					</ul>
					<h2></h2>
					<p></p>
					<ul class="lifeBuoys">
						<li class="lifeBuoy1"></li>
						<li class="lifeBuoy2"></li>
						<li class="lifeBuoy3"></li>
					</ul>
				</li>
				<li class="groupModeItem" id="groupModeItem_5">
					<ul class="points">
						<li></li>
						<li></li>
						<li></li>
						<li></li>
						<li></li>
						<li></li>
						<li></li>
						<li></li>
						<li></li>
						<li></li>
					</ul>
					<h2></h2>
					<p></p>
					<ul class="lifeBuoys">
						<li class="lifeBuoy1"></li>
						<li class="lifeBuoy2"></li>
						<li class="lifeBuoy3"></li>
					</ul>
				</li>
				<li class="groupModeItem" id="groupModeItem_6">
					<ul class="points">
						<li></li>
						<li></li>
						<li></li>
						<li></li>
						<li></li>
						<li></li>
						<li></li>
						<li></li>
						<li></li>
						<li></li>
					</ul>
					<h2></h2>
					<p></p>
					<ul class="lifeBuoys">
						<li class="lifeBuoy1"></li>
						<li class="lifeBuoy2"></li>
						<li class="lifeBuoy3"></li>
					</ul>
				</li>
				<li class="groupModeItem" id="groupModeItem_7">
					<ul class="points">
						<li></li>
						<li></li>
						<li></li>
						<li></li>
						<li></li>
						<li></li>
						<li></li>
						<li></li>
						<li></li>
						<li></li>
					</ul>
					<h2></h2>
					<p></p>
					<ul class="lifeBuoys">
						<li class="lifeBuoy1"></li>
						<li class="lifeBuoy2"></li>
						<li class="lifeBuoy3"></li>
					</ul>
				</li>
				<li class="groupModeItem" id="groupModeItem_8">
					<ul class="points">
						<li></li>
						<li></li>
						<li></li>
						<li></li>
						<li></li>
						<li></li>
						<li></li>
						<li></li>
						<li></li>
						<li></li>
					</ul>
					<h2></h2>
					<p></p>
					<ul class="lifeBuoys">
						<li class="lifeBuoy1"></li>
						<li class="lifeBuoy2"></li>
						<li class="lifeBuoy3"></li>
					</ul>
				</li>
				<li class="groupModeItem" id="groupModeItem_9">
					<ul class="points">
						<li></li>
						<li></li>
						<li></li>
						<li></li>
						<li></li>
						<li></li>
						<li></li>
						<li></li>
						<li></li>
						<li></li>
					</ul>
					<h2></h2>
					<p></p>
					<ul class="lifeBuoys">
						<li class="lifeBuoy1"></li>
						<li class="lifeBuoy2"></li>
						<li class="lifeBuoy3"></li>
					</ul>
				</li>
				<li class="groupModeItem" id="groupModeItem_10">
					<ul class="points">
						<li></li>
						<li></li>
						<li></li>
						<li></li>
						<li></li>
						<li></li>
						<li></li>
						<li></li>
						<li></li>
						<li></li>
					</ul>
					<h2></h2>
					<p></p>
					<ul class="lifeBuoys">
						<li class="lifeBuoy1"></li>
						<li class="lifeBuoy2"></li>
						<li class="lifeBuoy3"></li>
					</ul>
				</li>
				<li class="groupModeItem" id="groupModeItem_11">
					<ul class="points">
						<li></li>
						<li></li>
						<li></li>
						<li></li>
						<li></li>
						<li></li>
						<li></li>
						<li></li>
						<li></li>
						<li></li>
					</ul>
					<h2></h2>
					<p></p>
					<ul class="lifeBuoys">
						<li class="lifeBuoy1"></li>
						<li class="lifeBuoy2"></li>
						<li class="lifeBuoy3"></li>
					</ul>
				</li>
				<li class="groupModeItem" id="groupModeItem_12">
					<ul class="points">
						<li></li>
						<li></li>
						<li></li>
						<li></li>
						<li></li>
						<li></li>
						<li></li>
						<li></li>
						<li></li>
						<li></li>
					</ul>
					<h2></h2>
					<p></p>
					<ul class="lifeBuoys">
						<li class="lifeBuoy1"></li>
						<li class="lifeBuoy2"></li>
						<li class="lifeBuoy3"></li>
					</ul>
				</li>
			</ul>
		</div>
		<div id="unijna_stopka_space"></div>
	</div>
	<div style="position:absolute;overflow:hidden;height:1px;width:1px;top:-10px;">
		<div id="sound_tictac" class="jp-jplayer"></div>
		<div id="sound_ok" class="jp-jplayer"></div>
		<div id="sound_wrong" class="jp-jplayer"></div>
		<div id="jp_container_1" class="jp-audio">
			<div class="jp-type-single">
				<div class="jp-gui jp-interface">
					<ul class="jp-controls">
						<li><a href="javascript:;" class="jp-play" tabindex="1">play</a></li>
						<li><a href="javascript:;" class="jp-pause" tabindex="1">pause</a></li>
						<li><a href="javascript:;" class="jp-stop" tabindex="1">stop</a></li>
						<li><a href="javascript:;" class="jp-mute" tabindex="1" title="mute">mute</a></li>
						<li><a href="javascript:;" class="jp-unmute" tabindex="1" title="unmute">unmute</a></li>
						<li><a href="javascript:;" class="jp-volume-max" tabindex="1" title="max volume">max volume</a></li>
					</ul>
					<div class="jp-progress">
						<div class="jp-seek-bar">
							<div class="jp-play-bar"></div>
						</div>
					</div>
					<div class="jp-volume-bar">
						<div class="jp-volume-bar-value"></div>
					</div>
					<div class="jp-current-time"></div>
					<div class="jp-duration"></div>
					<ul class="jp-toggles">
						<li><a href="javascript:;" class="jp-repeat" tabindex="1" title="repeat">repeat</a></li>
						<li><a href="javascript:;" class="jp-repeat-off" tabindex="1" title="repeat off">repeat off</a></li>
					</ul>
				</div>
				<div class="jp-title">
					<ul>
						<li></li>
					</ul>
				</div>
				<div class="jp-no-solution">
				</div>
			</div>
		</div>
		<div id="jp_container_2" class="jp-audio">
			<div class="jp-type-single">
				<div class="jp-gui jp-interface">
					<ul class="jp-controls">
						<li><a href="javascript:;" class="jp-play" tabindex="1">play</a></li>
						<li><a href="javascript:;" class="jp-pause" tabindex="1">pause</a></li>
						<li><a href="javascript:;" class="jp-stop" tabindex="1">stop</a></li>
						<li><a href="javascript:;" class="jp-mute" tabindex="1" title="mute">mute</a></li>
						<li><a href="javascript:;" class="jp-unmute" tabindex="1" title="unmute">unmute</a></li>
						<li><a href="javascript:;" class="jp-volume-max" tabindex="1" title="max volume">max volume</a></li>
					</ul>
					<div class="jp-progress">
						<div class="jp-seek-bar">
							<div class="jp-play-bar"></div>

						</div>
					</div>
					<div class="jp-volume-bar">
						<div class="jp-volume-bar-value"></div>
					</div>
					<div class="jp-current-time"></div>
					<div class="jp-duration"></div>
					<ul class="jp-toggles">
						<li><a href="javascript:;" class="jp-repeat" tabindex="1" title="repeat">repeat</a></li>
						<li><a href="javascript:;" class="jp-repeat-off" tabindex="1" title="repeat off">repeat off</a></li>
					</ul>
				</div>
				<div class="jp-title">
					<ul>
						<li></li>
					</ul>
				</div>
				<div class="jp-no-solution">
				</div>
			</div>
		</div>
		<div id="jp_container_3" class="jp-audio">
			<div class="jp-type-single">
				<div class="jp-gui jp-interface">
					<ul class="jp-controls">
						<li><a href="javascript:;" class="jp-play" tabindex="1">play</a></li>
						<li><a href="javascript:;" class="jp-pause" tabindex="1">pause</a></li>
						<li><a href="javascript:;" class="jp-stop" tabindex="1">stop</a></li>
						<li><a href="javascript:;" class="jp-mute" tabindex="1" title="mute">mute</a></li>
						<li><a href="javascript:;" class="jp-unmute" tabindex="1" title="unmute">unmute</a></li>
						<li><a href="javascript:;" class="jp-volume-max" tabindex="1" title="max volume">max volume</a></li>
					</ul>
					<div class="jp-progress">
						<div class="jp-seek-bar">
							<div class="jp-play-bar"></div>

						</div>
					</div>
					<div class="jp-volume-bar">
						<div class="jp-volume-bar-value"></div>
					</div>
					<div class="jp-current-time"></div>
					<div class="jp-duration"></div>
					<ul class="jp-toggles">
						<li><a href="javascript:;" class="jp-repeat" tabindex="1" title="repeat">repeat</a></li>
						<li><a href="javascript:;" class="jp-repeat-off" tabindex="1" title="repeat off">repeat off</a></li>
					</ul>
				</div>
				<div class="jp-title">
					<ul>
						<li></li>
					</ul>
				</div>
				<div class="jp-no-solution">
				</div>
			</div>
		</div>
	</div>
<script type="text/javascript">
//<![CDATA[
$.cookie("LAST_NICK", '<?php echo $this->gameData['nick']; ?>', { expires: 7 });
$.cookie("LAST_PASS", '<?php echo $this->gameData['testPass']; ?>', { expires: 7 });
var gameData = '<?php
	// wyczyść w widoku zmienne które nie są nikomu potrzebne w tym miejscu
	$this->gameData['history'] = array(
		'questions' => array(),
		'answers' => array(),
		'answersTime' => array()
	);
	$this->gameData['test_data'] = array(
		'test' => array(),
		'questions' => array(),
		'answers' => array()
	);
	$this->gameData['lastQuestionAnswers'] = array(
	);
	echo json_encode($this->gameData);
?>';
// Zmienne globalne
var question_id = <?php echo $this->question->id; ?>;
var prev_question_id = 0;
var CAN_I_COUNT = true;
var CAN_I_CLICK = true;
if($.cookie("CAN_I_SOUND") == 'false' ) {
	var CAN_I_SOUND = false;
	$('#soundSwitch').children('div').addClass('off');
} else {
	var CAN_I_SOUND = true;
}
var SELECTED_ANSWER_ID = 0;
var BASE_URL = '<?php echo $this->baseUrl(); ?>';
var TICTAC_ALWAYS = <?php if(isset($this->app['tictac_always'])) { echo $this->app['tictac_always']; } else { echo '1'; } ?>;
var lifeBuoysPoints = 0;
// Teksty
var TXT_FLAGSEND = '<?php echo $this->translate('Uwagi zapisano i przesłano do administracji serwisu.'); ?>';
var TXT_POINTS = '<?php echo $this->translate('punktów'); ?>';
var TXT_TIME_IS_UP = "<?php echo $this->translate('Czas minął!'); ?>";
$(document).ready(function(){
	$("#sound_tictac").jPlayer({
		ready: function () {
			$(this).jPlayer("setMedia", {
				mp3:"http://headmaster.jestemprzedsiebiorczy.pl/sounds/tictac.mp3",
				oga:"http://headmaster.jestemprzedsiebiorczy.pl/sounds/tictac.ogg"
			}).jPlayer("load");
			if(gameData.timeLeft === gameData.time && gameData.step === 0) {
				$(this).jPlayer("play").jPlayer("pause")
			} else if(CAN_I_SOUND && TICTAC_ALWAYS == 1) {
				$(this).jPlayer("play");
			}			
		},
		swfPath: "js/jquery.jplayer",
		supplied: "mp3,oga",
		wmode: "window",
		loop: true
	});

	$("#sound_ok").jPlayer({
		ready: function () {
			$(this).jPlayer("setMedia", {
				mp3:"http://headmaster.jestemprzedsiebiorczy.pl/sounds/ok.mp3",
				oga:"http://headmaster.jestemprzedsiebiorczy.pl/sounds/ok.ogg"
			}).jPlayer("load").jPlayer("play").jPlayer("pause");
		},
		swfPath: "js/jquery.jplayer",
		cssSelectorAncestor: "#jp_container_2",
		supplied: "mp3,oga",
		wmode: "window"
	});

	$("#sound_wrong").jPlayer({
		ready: function () {
			$(this).jPlayer("setMedia", {
				mp3:"http://headmaster.jestemprzedsiebiorczy.pl/sounds/wrong.mp3",
				oga:"http://headmaster.jestemprzedsiebiorczy.pl/sounds/wrong.ogg"
			}).jPlayer("load").jPlayer("play").jPlayer("pause");
		},
		swfPath: "js/jquery.jplayer",
		cssSelectorAncestor: "#jp_container_3",
		supplied: "mp3,oga",
		wmode: "window"
	});
});
//]]>
</script>
<script src="<?php echo $this->baseUrl(); ?>/js/headmaster.js" type="text/javascript"></script>
