	<div id="pageWrapper">
		<div id="loginHeader" class="clearfix">
			<a href="<?php echo $this->baseUrl(); ?>"><img src="<?php echo $this->baseUrl(); ?>/img/headmaster_logo.png" alt="<?php echo $this->translate('HeadMaster'); ?>" class="logo" width="287" height="48" /></a>
		</div>
		<div id="login" class="clearfix">
			<div id="loginForm">
			<h2 class="center"><?php echo $this->translate('Podałeś nieprawidłowy klucz testu.'); ?></h2>
				<p class="center">
					<a href="<?php echo $this->baseUrl(); ?>"><?php echo $this->translate('Spróbuj jeszcze raz!'); ?></a>
				</p>
			</div>
		</div>
		<div id="unijna_stopka_space"></div>
	</div>
	<script type="text/javascript">
    //<![CDATA[
	$(document).ready(function() {
		$("#gameStart").validationEngine('attach',{
			'autoHidePrompt': true
		});
	});
    //]]>		
	</script>
