<?php
/**
 * @author <radoslaw.szczepaniak@gammanet.pl> Radosław Szczepaniak
 */

class CreateTableCvParams extends Doctrine_Migration_Base
{
    private $_tableName1 = 'cv_params';
    private $_tableName2 = 'name_params';

    protected $_firstNames = array(
        'Ada' => 0,
        'Adam' => 1,
        'Adrian' => 1,
        'Adrianna' => 0,
        'Agata' => 0,
        'Agnieszka' => 0,
        'Alan' => 1,
        'Aleksander' => 1,
        'Aleksandra' => 0,
        'Alex' => 1,
        'Alicja' => 0,
        'Amelia' => 0,
        'Anastazja' => 0,
        'Andrzej' => 1,
        'Angelika' => 0,
        'Aniela' => 0,
        'Anna' => 0,
        'Antoni' => 1,
        'Antonina' => 0,
        'Apolonia' => 0,
        'Arkadiusz' => 1,
        'Artur' => 1,
        'Barbara' => 0,
        'Bartek' => 1,
        'Blanka' => 0,
        'Borys' => 1,
        'Bruno' => 1,
        'Błażej' => 1,
        'Cezary' => 1,
        'Cyprian' => 1,
        'Dagmara' => 0,
        'Damian' => 1,
        'Daniel' => 1,
        'Daria' => 0,
        'Dawid' => 1,
        'Dominik' => 1,
        'Dominika' => 0,
        'Dorota' => 0,
        'Eliza' => 1,
        'Emil' => 1,
        'Emilia' => 0,
        'Eryk' => 1,
        'Ewa' => 0,
        'Ewelina' => 0,
        'Fabian' => 1,
        'Filip' => 1,
        'Franciszek' => 1,
        'Gabriel' => 1,
        'Gabriela' => 0,
        'Grzegorz' => 1,
        'Gustaw' => 1,
        'Hanna' => 0,
        'Helena' => 0,
        'Hubert' => 1,
        'Ida' => 0,
        'Iga' => 0,
        'Ignacy' => 1,
        'Igor' => 1,
        'Inga' => 0,
        'Iwo' => 1,
        'Izabela' => 0,
        'Jacek' => 1,
        'Jagoda' => 0,
        'Jakub' => 1,
        'Jan' => 1,
        'Jeremi' => 1,
        'Jerzy' => 1,
        'Joanna' => 0,
        'Julia' => 0,
        'Julian' => 1,
        'Julita' => 0,
        'Juliusz' => 1,
        'Justyna' => 0,
        'Józef' => 1,
        'Jędrzej' => 1,
        'Kacper' => 1,
        'Kaja' => 0,
        'Kajetan' => 1,
        'Kalina' => 0,
        'Kamil' => 1,
        'Kamila' => 0,
        'Karina' => 0,
        'Karol' => 1,
        'Karolina' => 0,
        'Katarzyna' => 0,
        'Kazimierz' => 1,
        'Kinga' => 0,
        'Klara' => 0,
        'Klaudia' => 0,
        'Konrad' => 1,
        'Konstancja' => 0,
        'Konstanty' => 1,
        'Kornel' => 1,
        'Kornelia' => 0,
        'Krystian' => 1,
        'Krystyna' => 0,
        'Krzysztof' => 1,
        'Ksawery' => 1,
        'Laura' => 0,
        'Lena' => 0,
        'Leon' => 1,
        'Lidia' => 0,
        'Liliana' => 0,
        'Liwia' => 0,
        'Luiza' => 0,
        'Maciej' => 1,
        'Magdalena' => 0,
        'Maja' => 0,
        'Maksym' => 1,
        'Maksymilian' => 1,
        'Malwina' => 0,
        'Marcel' => 1,
        'Marceli' => 1,
        'Marcelina' => 0,
        'Marcin' => 1,
        'Marek' => 1,
        'Maria' => 0,
        'Marianna' => 0,
        'Mariusz' => 1,
        'Marta' => 0,
        'Martyna' => 0,
        'Mateusz' => 1,
        'Matylda' => 0,
        'Małgorzata' => 0,
        'Melania' => 0,
        'Michalina' => 0,
        'Michał' => 1,
        'Mikołaj' => 1,
        'Milena' => 0,
        'Miłosz' => 1,
        'Monika' => 0,
        'Nadia' => 0,
        'Natalia' => 0,
        'Natasza' => 0,
        'Nela' => 0,
        'Nikodem' => 1,
        'Nikola' => 0,
        'Nina' => 0,
        'Norbert' => 1,
        'Olaf' => 1,
        'Olga' => 0,
        'Oliwia' => 0,
        'Oliwier' => 1,
        'Oskar' => 1,
        'Patrycja' => 0,
        'Patryk' => 1,
        'Paulina' => 0,
        'Paweł' => 1,
        'Piotr' => 1,
        'Pola' => 0,
        'Przemysław' => 1,
        'Radosław' => 1,
        'Rafał' => 1,
        'Robert' => 1,
        'Roksana' => 0,
        'Rozalia' => 0,
        'Ryszard' => 1,
        'Róża' => 0,
        'Sandra' => 0,
        'Sara' => 0,
        'Sebastian' => 1,
        'Sonia' => 0,
        'Stanisław' => 1,
        'Stefan' => 1,
        'Szymon' => 1,
        'Tadeusz' => 1,
        'Tomasz' => 1,
        'Tymon' => 1,
        'Tymoteusz' => 1,
        'Urszula' => 0,
        'Weronika' => 0,
        'Wiktor' => 1,
        'Wiktoria' => 0,
        'Witold' => 1,
        'Wojciech' => 1,
        'Zofia' => 0,
        'Zuzanna' => 0,
        'Łucja' => 0,
        'Łukasz' => 1,
    );

    protected $_lastNames = array (
        'Adamczyk' => 0,
        'Adamski' => 1,
        'Andrzejewski' => 1,
        'Baran' => 0,
        'Baranowski' => 1,
        'Barański' => 1,
        'Bednarczyk' => 0,
        'Bednarek' => 0,
        'Bednarski' => 1,
        'Bielecki' => 1,
        'Borkowski' => 1,
        'Borowski' => 1,
        'Brzeziński' => 1,
        'Brzozowski' => 1,
        'Bąk' => 0,
        'Błaszczyk' => 0,
        'Chmielewski' => 1,
        'Chojnacki' => 1,
        'Chrzanowski' => 1,
        'Ciesielski' => 1,
        'Cieślak' => 0,
        'Czajka' => 0,
        'Czajkowski' => 1,
        'Czarnecki' => 1,
        'Czech' => 0,
        'Czerwiński' => 1,
        'Dobrowolski' => 1,
        'Domagała' => 0,
        'Domański' => 1,
        'Duda' => 0,
        'Dudek' => 0,
        'Dziedzic' => 0,
        'Dąbrowski' => 1,
        'Dębski' => 1,
        'Gajda' => 0,
        'Gajewski' => 1,
        'Grabowski' => 1,
        'Grzelak' => 0,
        'Górecki' => 1,
        'Górski' => 1,
        'Głowacki' => 1,
        'Jabłoński' => 1,
        'Jakubowski' => 1,
        'Janicki' => 1,
        'Janik' => 0,
        'Janiszewski' => 1,
        'Jankowski' => 1,
        'Jarosz' => 0,
        'Jasiński' => 1,
        'Jastrzębski' => 1,
        'Jaworski' => 1,
        'Jóźwiak' => 0,
        'Kaczmarczyk' => 0,
        'Kaczmarek' => 0,
        'Kalinowski' => 1,
        'Kamiński' => 1,
        'Kania' => 0,
        'Karpiński' => 1,
        'Kasprzak' => 0,
        'Kaźmierczak' => 0,
        'Klimek' => 0,
        'Kopeć' => 0,
        'Kot' => 0,
        'Kowal' => 0,
        'Kowalczyk' => 0,
        'Kowalewski' => 1,
        'Kowalik' => 0,
        'Kowalski' => 1,
        'Kozak' => 0,
        'Kozioł' => 0,
        'Kozłowski' => 1,
        'Kołodziej' => 0,
        'Kołodziejczyk' => 0,
        'Krajewski' => 1,
        'Krawczyk' => 0,
        'Kruk' => 0,
        'Krupa' => 0,
        'Król' => 0,
        'Kubiak' => 0,
        'Kucharski' => 1,
        'Kurek' => 0,
        'Kurowski' => 1,
        'Kwiatkowski' => 1,
        'Kędzierski' => 1,
        'Laskowski' => 1,
        'Leszczyński' => 1,
        'Lewandowski' => 1,
        'Lipiński' => 1,
        'Lis' => 0,
        'Maciejewski' => 1,
        'Madej' => 0,
        'Maj' => 0,
        'Majchrzak' => 0,
        'Majewski' => 1,
        'Makowski' => 1,
        'Malinowski' => 1,
        'Marciniak' => 0,
        'Marcinkowski' => 1,
        'Marek' => 0,
        'Markiewicz' => 0,
        'Markowski' => 1,
        'Matusiak' => 0,
        'Matuszewski' => 1,
        'Mazur' => 0,
        'Mazurek' => 0,
        'Mazurkiewicz' => 0,
        'Małecki' => 1,
        'Michalak' => 0,
        'Michalski' => 1,
        'Mikołajczyk' => 0,
        'Milewski' => 1,
        'Mróz' => 0,
        'Mucha' => 0,
        'Musiał' => 0,
        'Nawrocki' => 1,
        'Nowacki' => 1,
        'Nowak' => 0,
        'Nowakowski' => 1,
        'Nowicki' => 1,
        'Olejniczak' => 0,
        'Olejnik' => 0,
        'Olszewski' => 1,
        'Orzechowski' => 1,
        'Orłowski' => 1,
        'Ostrowski' => 1,
        'Owczarek' => 0,
        'Pająk' => 0,
        'Pawlak' => 0,
        'Pawlik' => 0,
        'Pawłowski' => 1,
        'Piasecki' => 1,
        'Pietrzak' => 0,
        'Piotrowski' => 1,
        'Piątek' => 0,
        'Polak' => 0,
        'Przybylski' => 1,
        'Ratajczak' => 0,
        'Rogowski' => 1,
        'Romanowski' => 1,
        'Rutkowski' => 1,
        'Sadowski' => 1,
        'Sawicki' => 1,
        'Sikora' => 0,
        'Sikorski' => 1,
        'Skiba' => 0,
        'Skowroński' => 1,
        'Sobczak' => 0,
        'Sobolewski' => 1,
        'Socha' => 0,
        'Sokołowski' => 1,
        'Sosnowski' => 1,
        'Sowa' => 0,
        'Stankiewicz' => 0,
        'Stasiak' => 0,
        'Stefański' => 1,
        'Stępień' => 0,
        'Szczepaniak' => 0,
        'Szczepański' => 1,
        'Szewczyk' => 0,
        'Szulc' => 0,
        'Szymański' => 1,
        'Szymczak' => 0,
        'Tomaszewski' => 1,
        'Tomczak' => 0,
        'Tomczyk' => 0,
        'Urban' => 0,
        'Urbaniak' => 0,
        'Urbański' => 1,
        'Walczak' => 0,
        'Wasilewski' => 1,
        'Wawrzyniak' => 0,
        'Wesołowski' => 1,
        'Wieczorek' => 0,
        'Wierzbicki' => 1,
        'Wilczyński' => 1,
        'Wilk' => 0,
        'Witkowski' => 1,
        'Wiśniewski' => 1,
        'Wojciechowski' => 1,
        'Wolski' => 1,
        'Woźniak' => 0,
        'Wrona' => 0,
        'Wróbel' => 0,
        'Wróblewski' => 1,
        'Wysocki' => 1,
        'Wójcik' => 0,
        'Wójtowicz' => 0,
        'Włodarczyk' => 0,
        'Zając' => 0,
        'Zakrzewski' => 1,
        'Zalewski' => 1,
        'Zawadzki' => 1,
        'Zieliński' => 1,
        'Ziółkowski' => 1,
        'Zięba' => 0,
        'Łuczak' => 0,
        'Łukasik' => 0,
        'Śliwiński' => 1,
        'Żak' => 0,
    );

    public function up()
    {
         $this->createTable($this->_tableName1, array(
            'id' => array(
                'type' => 'integer',
                'primary' => true,
                'autoincrement' => true
            ),
            'education' => array(
                'type' => 'varchar(255)',
                'notnull' => false,
            ),
            'trade' => array(
                'type' => 'varchar(255)',
                'notnull' => false,
            ),
            'last_employer' => array(
                'type' => 'varchar(255)',
                'notnull' => false,
            )
        ));

        $this->createTable($this->_tableName2, array(
            'id' => array(
                'type' => 'integer',
                'notnull' => true,
                'autoincrement' => true,
                'primary' => true,
            ),
            'type' => array(
                'type' => 'smallint',
                'notnull' => true,
            ),
            'name' => array(
                'type' => 'varchar(32)',
                'notnull' => true,
            ),
            'sex' => array(
                'type' => 'varchar(1)',
                'notnull' => true,
            )
        ));
    }

    public function postUp()
    {
        Doctrine_Manager::connection()->exec(<<< SQL
INSERT INTO {$this->_tableName1} (id, education, trade, last_employer) VALUES
(1, 'Zawodowe: Szkoła Zawodowa', 'Praca biurowa', 'Calatron SA'),
(2, 'Zawodowe: Zasadnicza Szkoła Zawodowa', 'Budownictwo', 'PolTrans SA'),
(3, 'Średnie: Technikum Mechaniczne', 'Ogrodnictwo', 'WH Auto Poland SA'),
(4, 'Średnie: Technikum Gastronomiczne', 'Edukacja', 'Fratern SA'),
(5, 'Średnie: Technikum Samochodoe', 'Finanse', 'GyverCreativ Holding SA'),
(6, 'Średnie: Technikum Kolejowe', 'Praca w urzędzie', 'AzoTarn SA'),
(7, 'Średnie: Technikum Ekonomiczne', 'Motoryzacja', 'Holm Investig SA'),
(8, 'Średnie: Technikum Elektryczne', 'Tekstylna', 'Dębnica SA'),
(9, 'Średnie: Technikum Komunikacyjne', 'Odzieżowa', 'Szwarcwald SA'),
(10, 'Średnie: Technikum Leśne', 'Przemysł', 'Plast Stal SA'),
(11, 'Zawodowe: Liceum Zawodowe', 'Rolnictwo i leśnictwo', 'Skynet INC SA'),
(12, 'Średnie: Liceum Ogólnokształcące', 'Reozrywka i rekreacja', 'Peace Rest Hotels SA'),
(13, 'Średnie: Technikum Mechaniczne', 'Telekomunikacja i Internet', 'Olympia Research SA'),
(14, 'Średnie: Technikum Gastronomiczne', 'Turystyka', 'Rainbow Entertainment Group SA'),
(15, 'Średnie: Technikum Samochodoe', 'Usługi', 'Horus Hotels SA'),
(16, 'Średnie: Technikum Kolejowe', 'Gastronomia', 'Drewpol SA'),
(17, 'Średnie: Technikum Ekonomiczne', 'Zdrowie i uroda', 'Hardrex SA'),
(18, 'Średnie: Technikum Elektryczne', 'Ubezpieczenia', 'Petroprosper SA'),
(19, 'Średnie: Technikum Komunikacyjne', 'Transport', 'Gasoil Ventures SA'),
(20, 'Średnie: Technikum Leśne', 'Logistyka', 'NWO Investment SA'),
(21, 'Zawodowe: Liceum Zawodowe', NULL, 'Polsquat INC SA'),
(22, 'Średnie: Liceum Ogólnokształcące', NULL, 'Bankman SA'),
(23, 'Średnie: Liceum Pedagogiczne', NULL, 'Cinema Town International SA'),
(24, 'Średnie: Liceum Profilowane', NULL, 'AnalogGroup SA'),
(25, 'Zawodowe: Liceum Profilowane', NULL, 'Cyfrix SA'),
(26, 'Zawodowe: Liceum Profilowane', NULL, 'Cretide Holding SA'),
(27, 'Wyższe: Uniwersytet Jagielloński', NULL, 'Polkredyt SA'),
(28, 'Wyższe: Uniwersytet Warszawski', NULL, 'Ceramix INC SA'),
(29, 'Wyższe: Uniwersytet Marii Curie Skłodowskiej', NULL, 'Profekto SA'),
(30, 'Wyższe: Uniwersytet Łódzki', NULL, 'Granibud SA'),
(31, 'Wyższe: Uniwersytet Mikołaja Kopernika', NULL, 'Dekorator SA'),
(32, 'Wyższe: Uniwersytet Śląski', NULL, 'Izomaks SA'),
(33, 'Wyższe: Uniwersytet Gdański', NULL, 'Triton Shipment SA'),
(34, 'Wyższe: Uniwersytet Szczeciński', NULL, 'Palladium INC SA'),
(35, 'Wyższe: Uniwersytet Opolski', NULL, 'Zetoral SA'),
(36, 'Wyższe: Uniwersytet w Białymstoku', NULL, 'Financial Development SA'),
(37, 'Wyższe: Uniwersytet Warmińsko Mazurski', NULL, 'Real Estates Group SA'),
(38, 'Wyższe: Uniwersytet Kardynała Stefana Wyszyńskiego', NULL, 'Wincher Investment SA'),
(39, 'Wyższe: Uniwersytet Rzeszowski', NULL, 'Plaza Progress SA'),
(40, 'Wyższe: Uniwersytet Zielonogórski', NULL, 'Ronsal Holding Center SA'),
(41, 'Wyższe: Uniwersytet im. Kazimierza Wielkiego', NULL, 'Excalibur Arms SA'),
(42, 'Wyższe: Uniwersytet Medyczny w Łodzi', NULL, 'Foodmax SA'),
(43, 'Wyższe: Uniwersytet Technologiczno-Przyrodniczy im. Jana i Jędrzeja Śniadeckich w Bydgoszczy', NULL, 'Parnassus Imagine SA'),
(44, 'Wyższe: Uniwersytet Przyrodniczy we Wrocławiu', NULL, 'Patton Strategic SA'),
(45, 'Wyższe: Uniwersytet Medyczny im. Karola Marcinkowskiego w Poznaniu', NULL, 'Stix Travel SA'),
(46, 'Wyższe: Śląski Uniwersytet Medyczny w Katowicach', NULL, 'Confucius Research SA'),
(47, 'Wyższe: Uniwersytet Ekonomiczny w Krakowie', NULL, 'Swiss Center Group SA'),
(48, 'Wyższe: Warszawski Uniwersytet Medyczny', NULL, 'Playdorado SA'),
(49, 'Wyższe: Uniwersytet Medyczny w Lublinie', NULL, 'L-System SA'),
(50, 'Wyższe: Uniwersytet Medyczny w Białymstoku', NULL, 'Gammanet SA'),
(51, 'Wyższe: Uniwersytet Humanistyczno-Przyrodniczy Jana Kochanowskiego w Kielcach', NULL, 'Skaleks'),
(52, 'Wyższe: Uniwersytet Przyrodniczy w Poznaniu', NULL, NULL),
(53, 'Wyższe: Uniwersytet Przyrodniczy w Lublinie', NULL, NULL),
(54, 'Wyższe: Uniwersytet Rolniczy im. Hugona Kołłątaja w Krakowie', NULL, NULL),
(55, 'Wyższe: Uniwersytet Muzyczny Fryderyka Chopina w Warszawie', NULL, NULL),
(56, 'Wyższe: Uniwersytet Pedagogiczny im. Komisji Edukacji Narodowej w Krakowie', NULL, NULL),
(57, 'Wyższe: Uniwersytet Ekonomiczny w Poznaniu', NULL, NULL),
(58, 'Wyższe: Zachodniopomorski Uniwersytet Technologiczny w Szczecinie', NULL, NULL),
(59, 'Wyższe: Gdański Uniwersytet Medyczny', NULL, NULL),
(60, 'Wyższe: Uniwersytet Artystyczny w Poznaniu', NULL, NULL),
(61, 'Wyższe: Pomorski Uniwersytet Medyczny w Szczecinie', NULL, NULL),
(62, 'Wyższe: Uniwersytet Przyrodniczo-Humanistyczny w Siedlcach', NULL, NULL),
(63, 'Wyższe: Uniwersytet Ekonomiczny w Katowicach', NULL, NULL),
(64, 'Wyższe: Katolicki Uniwersytet Lubelski Jana Pawła II', NULL, NULL),
(65, 'Wyższe: Uniwersytet Papieski Jana Pawła II w Krakowie2', NULL, NULL),
(66, 'Wyższe: Politechnika Warszawska', NULL, NULL),
(67, 'Wyższe: Politechnika Gdańska', NULL, NULL),
(68, 'Wyższe: Politechnika Wrocławska', NULL, NULL),
(69, 'Wyższe: Akademia Górniczo-Hutnicza im. Stanisława Staszica', NULL, NULL),
(70, 'Wyższe: Politechnika Poznańska', NULL, NULL),
(71, 'Wyższe: Politechnika Łódzka', NULL, NULL),
(72, 'Wyższe: Politechnika Śląska', NULL, NULL),
(73, 'Wyższe: Politechnika Krakowska im. Tadeusza Kościuszki', NULL, NULL),
(74, 'Wyższe: Zachodniopomorski Uniwersytet Technologiczny', NULL, NULL),
(75, 'Wyższe: Politechnika Częstochowska', NULL, NULL),
(76, 'Wyższe: Politechnika Białostocka', NULL, NULL),
(77, 'Wyższe: Politechnika Radomska im. Kazimierza Pułaskiego', NULL, NULL),
(78, 'Wyższe: Uniwersytet Technologiczno-Przyrodniczy', NULL, NULL),
(79, 'Wyższe: Politechnika Rzeszowska im. Ignacego Łukasiewicza', NULL, NULL),
(80, 'Wyższe: Wojskowa Akademia Techniczna im. Jarosława Dąbrowskiego', NULL, NULL),
(81, 'Wyższe: Politechnika Lubelska', NULL, NULL),
(82, 'Wyższe: Politechnika Świętokrzyska', NULL, NULL),
(83, 'Wyższe: Uniwersytet Zielonogórski', NULL, NULL),
(84, 'Wyższe: Politechnika Opolska', NULL, NULL),
(85, 'Wyższe: Politechnika Koszalińska', NULL, NULL),
(86, 'Wyższe: Akademia Techniczno-Humanistyczna', NULL, NULL),
(87, 'Wyższe: Szkoła Główna Służby Pożarniczej', NULL, NULL),
(88, 'Wyższe: Szkoła Główna Handlowa', NULL, NULL),
(89, 'Wyższe: Wyższa Szkoła Zarządznia i Administracji w Opolu', NULL, NULL),
(90, 'Wyższe: Akademia Wychowania Fizycznego i Sportu im. Jędrzeja Śniadeckiego w Gdańsku', NULL, NULL),
(91, 'Wyższe: Akademia Wychowania Fizycznego im. Jerzego Kukuczki w Katowicach', NULL, NULL),
(92, 'Wyższe: Akademia Wychowania Fizycznego im. Bronisława Czecha w Krakowie', NULL, NULL),
(93, 'Wyższe: Akademia Wychowania Fizycznego im. Eugeniusza Piaseckiego w Poznaniu', NULL, NULL),
(94, 'Wyższe: Zamiejscowy Wydział Kultury Fizycznej w Gorzowie Wielkopolskim', NULL, NULL),
(95, 'Wyższe: Akademia Wychowania Fizycznego Józefa Piłsudskiego w Warszawie', NULL, NULL),
(96, 'Wyższe: Zamiejscowy Wydział Wychowania Fizycznego w Białej Podlaskiej', NULL, NULL),
(97, 'Wyższe: Akademia Wychowania Fizycznego we Wrocławiu', NULL, NULL),
(98, 'Zawodowe: Szkoła Zawodowa', NULL, NULL),
(99, 'Zawodowe: Zasadnicza Szkoła Zawodowa', NULL, NULL),
(100, 'Średnie: Technikum Mechaniczne', NULL, NULL),
(101, 'Średnie: Technikum Gastronomiczne', NULL, NULL),
(102, 'Średnie: Technikum Samochodoe', NULL, NULL),
(103, 'Średnie: Technikum Kolejowe', NULL, NULL),
(104, 'Średnie: Technikum Ekonomiczne', NULL, NULL),
(105, 'Średnie: Technikum Elektryczne', NULL, NULL),
(106, 'Średnie: Technikum Komunikacyjne', NULL, NULL),
(107, 'Średnie: Technikum Leśne', NULL, NULL),
(108, 'Zawodowe: Liceum Zawodowe', NULL, NULL),
(109, 'Średnie: Liceum Ogólnokształcące', NULL, NULL),
(110, 'Średnie: Technikum Mechaniczne', NULL, NULL),
(111, 'Średnie: Technikum Gastronomiczne', NULL, NULL),
(112, 'Średnie: Technikum Samochodoe', NULL, NULL),
(113, 'Średnie: Technikum Kolejowe', NULL, NULL),
(114, 'Średnie: Technikum Ekonomiczne', NULL, NULL),
(115, 'Średnie: Technikum Elektryczne', NULL, NULL),
(116, 'Średnie: Technikum Komunikacyjne', NULL, NULL),
(117, 'Średnie: Technikum Leśne', NULL, NULL),
(118, 'Zawodowe: Liceum Zawodowe', NULL, NULL),
(119, 'Średnie: Liceum Ogólnokształcące', NULL, NULL),
(120, 'Średnie: Liceum Pedagogiczne', NULL, NULL),
(121, 'Średnie: Liceum Profilowane', NULL, NULL),
(122, 'Zawodowe: Liceum Profilowane', NULL, NULL),
(123, 'Zawodowe: Liceum Profilowane', NULL, NULL),
(124, 'Zawodowe: Szkoła Zawodowa', NULL, NULL),
(125, 'Zawodowe: Zasadnicza Szkoła Zawodowa', NULL, NULL),
(126, 'Średnie: Technikum Mechaniczne', NULL, NULL),
(127, 'Średnie: Technikum Gastronomiczne', NULL, NULL),
(128, 'Średnie: Technikum Samochodoe', NULL, NULL),
(129, 'Średnie: Technikum Kolejowe', NULL, NULL),
(130, 'Średnie: Technikum Ekonomiczne', NULL, NULL),
(131, 'Średnie: Technikum Elektryczne', NULL, NULL),
(132, 'Średnie: Technikum Komunikacyjne', NULL, NULL),
(133, 'Średnie: Technikum Leśne', NULL, NULL),
(134, 'Zawodowe: Liceum Zawodowe', NULL, NULL),
(135, 'Średnie: Liceum Ogólnokształcące', NULL, NULL),
(136, 'Średnie: Technikum Mechaniczne', NULL, NULL),
(137, 'Średnie: Technikum Gastronomiczne', NULL, NULL),
(138, 'Średnie: Technikum Samochodoe', NULL, NULL),
(139, 'Średnie: Technikum Kolejowe', NULL, NULL),
(140, 'Średnie: Technikum Ekonomiczne', NULL, NULL),
(141, 'Średnie: Technikum Elektryczne', NULL, NULL),
(142, 'Średnie: Technikum Komunikacyjne', NULL, NULL),
(143, 'Średnie: Technikum Leśne', NULL, NULL),
(144, 'Zawodowe: Liceum Zawodowe', NULL, NULL),
(145, 'Średnie: Liceum Ogólnokształcące', NULL, NULL),
(146, 'Średnie: Liceum Pedagogiczne', NULL, NULL),
(147, 'Średnie: Liceum Profilowane', NULL, NULL),
(148, 'Zawodowe: Liceum Profilowane', NULL, NULL),
(149, 'Zawodowe: Liceum Profilowane', NULL, NULL),
(150, 'Zawodowe: Szkoła Zawodowa', NULL, NULL),
(151, 'Zawodowe: Zasadnicza Szkoła Zawodowa', NULL, NULL),
(152, 'Średnie: Technikum Mechaniczne', NULL, NULL),
(153, 'Średnie: Technikum Gastronomiczne', NULL, NULL),
(154, 'Średnie: Technikum Samochodoe', NULL, NULL),
(155, 'Średnie: Technikum Kolejowe', NULL, NULL),
(156, 'Średnie: Technikum Ekonomiczne', NULL, NULL),
(157, 'Średnie: Technikum Elektryczne', NULL, NULL),
(158, 'Średnie: Technikum Komunikacyjne', NULL, NULL),
(159, 'Średnie: Technikum Leśne', NULL, NULL),
(160, 'Zawodowe: Liceum Zawodowe', NULL, NULL),
(161, 'Średnie: Liceum Ogólnokształcące', NULL, NULL),
(162, 'Średnie: Technikum Mechaniczne', NULL, NULL),
(163, 'Średnie: Technikum Gastronomiczne', NULL, NULL),
(164, 'Średnie: Technikum Samochodoe', NULL, NULL),
(165, 'Średnie: Technikum Kolejowe', NULL, NULL),
(166, 'Średnie: Technikum Ekonomiczne', NULL, NULL),
(167, 'Średnie: Technikum Elektryczne', NULL, NULL),
(168, 'Średnie: Technikum Komunikacyjne', NULL, NULL),
(169, 'Średnie: Technikum Leśne', NULL, NULL),
(170, 'Zawodowe: Liceum Zawodowe', NULL, NULL),
(171, 'Średnie: Liceum Ogólnokształcące', NULL, NULL),
(172, 'Średnie: Liceum Pedagogiczne', NULL, NULL),
(173, 'Średnie: Liceum Profilowane', NULL, NULL),
(174, 'Zawodowe: Liceum Profilowane', NULL, NULL),
(175, 'Zawodowe: Liceum Profilowane', NULL, NULL),
(176, 'Zawodowe: Szkoła Zawodowa', NULL, NULL),
(177, 'Zawodowe: Zasadnicza Szkoła Zawodowa', NULL, NULL),
(178, 'Średnie: Technikum Mechaniczne', NULL, NULL),
(179, 'Średnie: Technikum Gastronomiczne', NULL, NULL),
(180, 'Średnie: Technikum Samochodoe', NULL, NULL),
(181, 'Średnie: Technikum Kolejowe', NULL, NULL),
(182, 'Średnie: Technikum Ekonomiczne', NULL, NULL),
(183, 'Średnie: Technikum Elektryczne', NULL, NULL),
(184, 'Średnie: Technikum Komunikacyjne', NULL, NULL),
(185, 'Średnie: Technikum Leśne', NULL, NULL),
(186, 'Zawodowe: Liceum Zawodowe', NULL, NULL),
(187, 'Średnie: Liceum Ogólnokształcące', NULL, NULL),
(188, 'Średnie: Technikum Mechaniczne', NULL, NULL),
(189, 'Średnie: Technikum Gastronomiczne', NULL, NULL),
(190, 'Średnie: Technikum Samochodoe', NULL, NULL),
(191, 'Średnie: Technikum Kolejowe', NULL, NULL),
(192, 'Średnie: Technikum Ekonomiczne', NULL, NULL),
(193, 'Średnie: Technikum Elektryczne', NULL, NULL),
(194, 'Średnie: Technikum Komunikacyjne', NULL, NULL),
(195, 'Średnie: Technikum Leśne', NULL, NULL),
(196, 'Zawodowe: Liceum Zawodowe', NULL, NULL),
(197, 'Średnie: Liceum Ogólnokształcące', NULL, NULL),
(198, 'Średnie: Liceum Pedagogiczne', NULL, NULL),
(199, 'Średnie: Liceum Profilowane', NULL, NULL),
(200, 'Zawodowe: Liceum Profilowane', NULL, NULL),
(201, 'Zawodowe: Liceum Profilowane', NULL, NULL),
(202, 'Zawodowe: Szkoła Zawodowa', NULL, NULL),
(203, 'Zawodowe: Zasadnicza Szkoła Zawodowa', NULL, NULL),
(204, 'Średnie: Technikum Mechaniczne', NULL, NULL),
(205, 'Średnie: Technikum Gastronomiczne', NULL, NULL),
(206, 'Średnie: Technikum Samochodoe', NULL, NULL),
(207, 'Średnie: Technikum Kolejowe', NULL, NULL),
(208, 'Średnie: Technikum Ekonomiczne', NULL, NULL),
(209, 'Średnie: Technikum Elektryczne', NULL, NULL),
(210, 'Średnie: Technikum Komunikacyjne', NULL, NULL),
(211, 'Średnie: Technikum Leśne', NULL, NULL),
(212, 'Zawodowe: Liceum Zawodowe', NULL, NULL),
(213, 'Średnie: Liceum Ogólnokształcące', NULL, NULL),
(214, 'Średnie: Technikum Mechaniczne', NULL, NULL),
(215, 'Średnie: Technikum Gastronomiczne', NULL, NULL),
(216, 'Średnie: Technikum Samochodoe', NULL, NULL),
(217, 'Średnie: Technikum Kolejowe', NULL, NULL),
(218, 'Średnie: Technikum Ekonomiczne', NULL, NULL),
(219, 'Średnie: Technikum Elektryczne', NULL, NULL),
(220, 'Średnie: Technikum Komunikacyjne', NULL, NULL),
(221, 'Średnie: Technikum Leśne', NULL, NULL),
(222, 'Zawodowe: Liceum Zawodowe', NULL, NULL),
(223, 'Średnie: Liceum Ogólnokształcące', NULL, NULL),
(224, 'Średnie: Liceum Pedagogiczne', NULL, NULL),
(225, 'Średnie: Liceum Profilowane', NULL, NULL),
(226, 'Zawodowe: Liceum Profilowane', NULL, NULL),
(227, 'Zawodowe: Liceum Profilowane', NULL, NULL),
(228, 'Zawodowe: Szkoła Zawodowa', NULL, NULL),
(229, 'Zawodowe: Zasadnicza Szkoła Zawodowa', NULL, NULL),
(230, 'Średnie: Technikum Mechaniczne', NULL, NULL),
(231, 'Średnie: Technikum Gastronomiczne', NULL, NULL),
(232, 'Średnie: Technikum Samochodoe', NULL, NULL),
(233, 'Średnie: Technikum Kolejowe', NULL, NULL),
(234, 'Średnie: Technikum Ekonomiczne', NULL, NULL),
(235, 'Średnie: Technikum Elektryczne', NULL, NULL),
(236, 'Średnie: Technikum Komunikacyjne', NULL, NULL),
(237, 'Średnie: Technikum Leśne', NULL, NULL),
(238, 'Zawodowe: Liceum Zawodowe', NULL, NULL),
(239, 'Średnie: Liceum Ogólnokształcące', NULL, NULL),
(240, 'Średnie: Technikum Mechaniczne', NULL, NULL),
(241, 'Średnie: Technikum Gastronomiczne', NULL, NULL),
(242, 'Średnie: Technikum Samochodoe', NULL, NULL),
(243, 'Średnie: Technikum Kolejowe', NULL, NULL),
(244, 'Średnie: Technikum Ekonomiczne', NULL, NULL),
(245, 'Średnie: Technikum Elektryczne', NULL, NULL),
(246, 'Średnie: Technikum Komunikacyjne', NULL, NULL),
(247, 'Średnie: Technikum Leśne', NULL, NULL),
(248, 'Zawodowe: Liceum Zawodowe', NULL, NULL),
(249, 'Średnie: Liceum Ogólnokształcące', NULL, NULL),
(250, 'Średnie: Liceum Pedagogiczne', NULL, NULL),
(251, 'Średnie: Liceum Profilowane', NULL, NULL),
(252, 'Zawodowe: Liceum Profilowane', NULL, NULL),
(253, 'Zawodowe: Liceum Profilowane', NULL, NULL),
(254, 'Zawodowe: Szkoła Zawodowa', NULL, NULL),
(255, 'Zawodowe: Zasadnicza Szkoła Zawodowa', NULL, NULL),
(256, 'Średnie: Technikum Mechaniczne', NULL, NULL),
(257, 'Średnie: Technikum Gastronomiczne', NULL, NULL),
(258, 'Średnie: Technikum Samochodoe', NULL, NULL),
(259, 'Średnie: Technikum Kolejowe', NULL, NULL),
(260, 'Średnie: Technikum Ekonomiczne', NULL, NULL),
(261, 'Średnie: Technikum Elektryczne', NULL, NULL),
(262, 'Średnie: Technikum Komunikacyjne', NULL, NULL),
(263, 'Średnie: Technikum Leśne', NULL, NULL),
(264, 'Zawodowe: Liceum Zawodowe', NULL, NULL),
(265, 'Średnie: Liceum Ogólnokształcące', NULL, NULL),
(266, 'Średnie: Technikum Mechaniczne', NULL, NULL),
(267, 'Średnie: Technikum Gastronomiczne', NULL, NULL),
(268, 'Średnie: Technikum Samochodoe', NULL, NULL),
(269, 'Średnie: Technikum Kolejowe', NULL, NULL),
(270, 'Średnie: Technikum Ekonomiczne', NULL, NULL),
(271, 'Średnie: Technikum Elektryczne', NULL, NULL),
(272, 'Średnie: Technikum Komunikacyjne', NULL, NULL),
(273, 'Średnie: Technikum Leśne', NULL, NULL),
(274, 'Zawodowe: Liceum Zawodowe', NULL, NULL),
(275, 'Średnie: Liceum Ogólnokształcące', NULL, NULL),
(276, 'Średnie: Liceum Pedagogiczne', NULL, NULL),
(277, 'Średnie: Liceum Profilowane', NULL, NULL),
(278, 'Zawodowe: Liceum Profilowane', NULL, NULL),
(279, 'Zawodowe: Liceum Profilowane', NULL, NULL),
(280, 'Zawodowe: Szkoła Zawodowa', NULL, NULL),
(281, 'Zawodowe: Zasadnicza Szkoła Zawodowa', NULL, NULL),
(282, 'Średnie: Technikum Mechaniczne', NULL, NULL),
(283, 'Średnie: Technikum Gastronomiczne', NULL, NULL),
(284, 'Średnie: Technikum Samochodoe', NULL, NULL),
(285, 'Średnie: Technikum Kolejowe', NULL, NULL),
(286, 'Średnie: Technikum Ekonomiczne', NULL, NULL),
(287, 'Średnie: Technikum Elektryczne', NULL, NULL),
(288, 'Średnie: Technikum Komunikacyjne', NULL, NULL),
(289, 'Średnie: Technikum Leśne', NULL, NULL),
(290, 'Zawodowe: Liceum Zawodowe', NULL, NULL),
(291, 'Średnie: Liceum Ogólnokształcące', NULL, NULL),
(292, 'Średnie: Technikum Mechaniczne', NULL, NULL),
(293, 'Średnie: Technikum Gastronomiczne', NULL, NULL),
(294, 'Średnie: Technikum Samochodoe', NULL, NULL),
(295, 'Średnie: Technikum Kolejowe', NULL, NULL),
(296, 'Średnie: Technikum Ekonomiczne', NULL, NULL),
(297, 'Średnie: Technikum Elektryczne', NULL, NULL),
(298, 'Średnie: Technikum Komunikacyjne', NULL, NULL),
(299, 'Średnie: Technikum Leśne', NULL, NULL),
(300, 'Zawodowe: Liceum Zawodowe', NULL, NULL),
(301, 'Średnie: Liceum Ogólnokształcące', NULL, NULL),
(302, 'Średnie: Liceum Pedagogiczne', NULL, NULL),
(303, 'Średnie: Liceum Profilowane', NULL, NULL),
(304, 'Zawodowe: Liceum Profilowane', NULL, NULL),
(305, 'Zawodowe: Liceum Profilowane', NULL, NULL);
SQL
        );

        foreach ($this->_firstNames as $name => $male) {
            Doctrine_Manager::connection()->exec('INSERT INTO ' . $this->_tableName2 . ' (type, name, sex) VALUES (?, ?, ?)', array(0, $name, $male ? 'M' : 'F'));
        }

        foreach ($this->_lastNames as $name => $male) {
            Doctrine_Manager::connection()->exec('INSERT INTO ' . $this->_tableName2 . ' (type, name, sex) VALUES (?, ?, ?)', array(1, $name, $male ? 'M' : 'F'));
        }
    }

    public function down()
    {
        $this->dropTable($this->_tableName2);
        $this->dropTable($this->_tableName1);
    }
}