<?php if ($this->pageCount > 1): ?>
<?php $params = Zend_Controller_Front::getInstance()->getRequest()->getParams(); ?>
<div class="paginator">
    <?php if ($this->previous): $params['pageID'] = $this->previous; ?><a class="prev" href="<?php echo $this->url($params) ?>" title="<?php echo $this->translate('paginator previous') ?>">&laquo;</a><?php endif ?>
    <?php if (!in_array($this->first, $this->pagesInRange)): ?><a href="<?php $params['pageID'] = $this->first; echo $this->url($params) ?>" title="<?php echo $this->translate('paginator first') ?>"><?php echo $this->first ?></a> <span>&hellip;</span><?php endif ?>

    <?php foreach ($this->pagesInRange as $pageID): ?>
        <?php if ($pageID == $this->current): ?>
            <a class="active"><?php echo $pageID ?></a>
        <?php else: $params['pageID'] = $pageID; ?>
            <a href="<?php echo $this->url($params) ?>" title="<?php echo $this->translate('paginator page %s', $pageID) ?>"><?php echo $pageID ?></a>
        <?php endif ?>
    <?php endforeach ?>

    <?php if (!in_array($this->last, $this->pagesInRange)): ?><span>&hellip;</span> <a href="<?php $params['pageID'] = $this->last; echo $this->url($params) ?>" title="<?php echo $this->translate('paginator last') ?>"><?php echo $this->last ?></a><?php endif ?>
    <?php if ($this->next): $params['pageID'] = $this->next; ?><a class="next" href="<?php echo $this->url($params) ?>" title="<?php echo $this->translate('paginator next') ?>">&raquo;</a><?php endif ?>
</div>
<?php endif ?>
