<?php
/**
 * @author <marcin.kurczewski@gammanet.pl> Marcin Kurczewski
 */
if (isset($this->response))
{
	if (isset($this->response['outputJSON']['message']))
	{
		echo '<p class="notice error">Błąd: ' . $this->response['outputJSON']['message'] . '</p>';
	}
	elseif ($this->response['outputStatusCode'] == 200)
	{
		header('Location: ' . $this->url(array('controller' => 'resources', 'action' => 'index'), null, false));
		echo '<p class="notice">Zasób edytowany z sukcesem.</p>';
	}
	else
	{
		echo '<p class="notice error">Wystąpiły błędy podczas próby edycji zasobu.</p>';
	}
}
else
{
	if (isset($this->record['outputJSON']['id']))
	{
?>
<div class="op shaded">
	<ul class="op">
		<li class="icon-return"><a class="icon-cancel icon-return" href="<?php echo $this->url(array('controller' => 'resources', 'action' => 'index'), null, false); ?>">Powrót</a></li>
	</ul>
</div>

<form id="resource-edit-form" action="<?php echo $this->url(array('controller' => 'resources', 'action' => 'edit', 'id' => $this->record['outputJSON']['id']), null, false); ?>" method="post">
	<fieldset>
		<legend><?php echo $this->record['outputJSON']['name']; ?></legend>
		<div>
			<label for="edit-name">Nazwa zasobu</label>
			<input id="edit-name" class="required name" name="name" value="<?php echo $this->record['outputJSON']['name']; ?>">
		</div>
	</fieldset>
	<div class="op">
		<button class="button default action-update" name="submit-action" type="submit" value="edit">Aktualizuj</button>
		<button class="button action-cancel" name="submit-action" type="button" value="cancel" onclick="window.location.href='<?php echo $this->url(array('controller' => 'resources', 'action' => 'index'), null, false); ?>'; return false; ">Anuluj</button>
	</div>
</form>
<?php
	}
	else
	{
?>
	<p class="notice error">Błąd: wybrany zasób nie istnieje.</p>
<?php
	}
}
?>
