<?php
/**
 * @author <marcin.kurczewski@gammanet.pl> Marcin Kurczewski
 */
if (isset($this->response))
{
	if (isset($this->response['outputJSON']['message']))
	{
		echo '<p class="notice error">Błąd: ' . $this->response['outputJSON']['message'] . '</p>';
	}
	elseif (isset($this->response['outputJSON']['id']))
	{
		header('Location: ' . $this->url(array('controller' => 'courses', 'action' => 'index'), null, false));
		echo '<p class="notice">Szkolenie dodane z sukcesem.</p>';
	}
	else
	{
		echo '<p class="notice error">Wystąpiły błędy podczas próby dodania szkolenia.</p>';
	}
}
else
{
	$this->headScript()->appendFile($this->baseUrl('js/entity-editor.js'));
?>
<div class="op shaded">
	<ul class="op">
		<li class="icon-return"><a class="action-cancel action-return" href="<?php echo $this->url(array('controller' => 'courses', 'action' => 'index'), null, true); ?>">Powrót</a></li>
	</ul>
</div>

<form id="courses-form" action="<?php echo $this->url(array('controller' => 'courses', 'action' => 'create'), null, true); ?>" method="post">
	<ul class="tab-switcher">
		<li>Dane podstawowe</li>
		<li>Opis szkolenia</li>
		<li>Jednostki szkoleniowe</li>
	</ul>

	<div class="tabs">

		<div class="tab">
			<fieldset>
				<div>
					<label for="edit-name">Nazwa szkolenia</label>
					<input class="required name" id="edit-name" name="name">
				</div>
				<div>
					<label for="edit-code">Kod szkolenia</label>
					<input class="required code" id="edit-code" name="code">
				</div>
				<div>
					<label for="edit-color">Kolor szkolenia</label>
					<input class="color" id="edit-color" name="color">
				</div>
				<div>
					<label for="edit-training-center">Ośrodek</label>
					<div id="edit-training-center">
						<select name="training-center-id">
							<?php
								foreach ($this->trainingCenters['outputJSON'] as $i => $trainingCenter)
								{
									$sel = $i == 0;
									echo '<option' . ($sel ? ' selected="selected="' : '') . ' value="' . $trainingCenter['id'] . '">' . $trainingCenter['name'] . '</option>';
								}
							?>
						</select>
					</div>
				</div>
				<div>
					<label for="edit-group">Grupa szkoleniowa</label>
					<div id="edit-group">
						<select name="group-id">
							<?php
								foreach ($this->groups['outputJSON'] as $i => $group)
								{
									$sel = $i == 0;
									echo '<option' . ($sel ? ' selected="selected"' : '') . ' value="' . $group['id'] . '">' . $group['name'] . '</option>';
								}
							?>
						</select>
					</div>
				</div>
				<div>
					<label for="edit-price">Cena szkolenia</label>
					<input class="integer non-negative-integer" id="edit-price" name="price">
				</div>
				<div>
					<label for="edit-advance-level">Poziom</label>
					<select id="edit-advance-level" name="advance-level">
						<?php
							$elems = array
							(
								array('key' => 0, 'text' => 'Nie dotyczy'),
								array('key' => 1, 'text' => 'Podstawowy'),
								array('key' => 2, 'text' => 'Średni'),
								array('key' => 3, 'text' => 'Zaawansowany')
							);
							foreach ($elems as $elem)
							{
								echo '<option value="' . $elem['key'] . '">' . $elem['text'] . '</option>';
							}
						?>
					</select>
				</div>
				<div>
					<label for="edit-project">Projekt</label>
					<div id="edit-project">
						<select name="project-id">
							<?php
								foreach ($this->projects['outputJSON'] as $i => $project)
								{
									$sel = $i == 0;
									echo '<option' . ($sel ? ' selected="selected"' : '') . ' value="' . $project['id'] . '">' . $project['name'] . '</option>';
								}
							?>
						</select>
					</div>
				</div>
				<div>
					<label for="edit-status">Status</label>
					<select id="edit-status" name="status">
						<?php
							$elems = array
							(
								array('key' => 1, 'text' => 'Bieżące'),
								array('key' => 2, 'text' => 'Planowane'),
								array('key' => 3, 'text' => 'Archiwalne')
							);
							foreach ($elems as $elem)
							{
								echo '<option value="' . $elem['key'] . '">' . $elem['text'] . '</option>';
							}
						?>
					</select>
				</div>
				<div>
					<label for="edit-show-on-www" >Pokaż na WWW</label>
					<input type="checkbox" id="edit-show-on-www" name="show-on-www">
				</div>
			</table>
		</div>

		<div class="tab">
			<textarea class="richtext" name="description"></textarea>
		</div>

		<div class="tab">
			<div id="unit-editor"></div>
		</div>

	</div>

	<div class="op">
		<button class="button default action-add" name="submit-action" type="submit" value="create">Utwórz</button>
		<button class="button action-cancel" name="submit-action" type="button" value="cancel" onclick="window.location.href='<?php echo $this->url(array('controller' => 'courses', 'action' => 'index'), null, true); ?>'; return false; ">Anuluj</button>
	</div>

	<input type="hidden" name="trainers-source" value="<?php
		$trainers = array();
		foreach ($this->trainers['outputJSON'] as $trainer)
		{
			$trainers [$trainer['id']] = $trainer['first_name'] . ' ' . $trainer['last_name'];
		}
		echo htmlspecialchars(json_encode($trainers));
		?>">
	<input type="hidden" name="unit-data">
</form>
<?php
}
?>
