<div class="mainscreen_in">
	<div class="mainscreen_contener">
		<ul class="mainscreen_points">
			<li class="m_points_1">
				<h2><?php echo $this->translate('mainscreen_1_title'); ?></h2>
				<p><?php echo $this->translate('mainscreen_1_desc'); ?></p>
			</li>
			<li class="m_points_2">
				<h2><?php echo $this->translate('mainscreen_2_title'); ?></h2>
				<p><?php echo $this->translate('mainscreen_2_desc'); ?></p>
			</li>
			<li class="m_points_3">
				<h2><?php echo $this->translate('mainscreen_3_title'); ?></h2>
				<p><?php echo $this->translate('mainscreen_3_desc'); ?></p>
			</li>
			<li class="m_points_4">
				<h2><?php echo $this->translate('mainscreen_4_title'); ?></h2>
				<p><?php echo $this->translate('mainscreen_4_desc'); ?></p>
			</li>
		</ul>
		<div class="login balloon">
			<h1><?php echo $this->translate('application_title') ?></h1>
			<p><?php echo $this->translate('auth_login_text') ?></p>
			<a class="btn btn-primary" href="<?php echo $this->url(array('action' => 'open-id', 'controller' => 'auth'), null, true) ?>">
				<?php echo $this->translate('auth_login_button') ?>
			</a>
		</div>
		<div class="clear"></div>
	</div>
</div>

