<?php if (!empty($this->payment)): ?>
	<form action="https://www.platnosci.pl/paygw/UTF/NewPayment" method="POST" name="payform">
		<?php
			$params = array (
				'pos_id' => $this->paymentOptions['payu']['pos_id'],
				'pos_auth_key' => $this->paymentOptions['payu']['pos_auth_key'],
				'session_id' => $this->payment->custom_id,
				'amount' => $this->payment->amount * 100,
				'desc' => 'Shared Apps',
				'client_ip' => $_SERVER['REMOTE_ADDR'],
				'first_name' => $this->paymentOptions['payu']['first_name'],
				'last_name' => $this->paymentOptions['payu']['last_name'],
				'email' => $this->paymentOptions['payu']['email'],
			);
			foreach ($params as $key => $value) {
				echo PHP_EOL . $this->formHidden($key, $value);
			}
		?>
	</form>
	<script type="text/javascript">
		document.forms['payform'].submit();
	</script>
<?php else: ?>
	<div class="payment">
		<h1><?php echo $this->translate('payment summary') ?></h1>

		<table>
			<thead>
				<tr>
					<th class="user"><?php echo $this->translate('payment user') ?></th>
					<th class="expires"><?php echo $this->translate('payment expires') ?></th>
					<th class="expires-new"><?php echo $this->translate('payment expires new') ?></th>
					<th class="amount"><?php echo $this->translate('payment amount') ?></th>
				</tr>
			</thead>
			<tbody>
				<?php foreach (Model_Payment::getUsersFromCustom($this->custom) as $u): ?>
					<tr>
						<td class="user"><?php echo $u->email ?></td>
						<td class="expires"><?php $tmp = new DateTime($u->expire); echo $tmp->format($this->translate('common_date_format')) ?></td>
						<td class="expires-new"><?php $tmp = new DateTime($u->expire); $tmp->add(new DateInterval('P'.$this->paymentOptions['fee'][$u->fee_type]['interval'])); echo $tmp->format($this->translate('common_date_format')) ?></td>
						<td class="user"><?php echo $this->paymentOptions['fee'][$u->fee_type]['amount'][$this->typeString] . ' ' . $this->paymentOptions[$this->typeString]['currency']; ?></td>
					</tr>
				<?php endforeach ?>
			</tbody>
			<tfoot>
				<tr>
					<td class="amount-total" colspan="3"><?php echo $this->translate('payment amount total') ?></td>
					<td class="amount"><?php echo $this->amount . ' ' . $this->paymentOptions[$this->typeString]['currency'] ?></td>
				</tr>
			</tfoot>
		</table>

		<form method="post">
			<?php echo $this->formHidden('data', $this->data) ?>
			<?php echo $this->formHidden('type', $this->type) ?>
			<?php echo $this->formHidden('submit', '1') ?>
			<button class="btn btn-large btn-primary" type="submit"><?php echo $this->translate('payment confirm') ?></button>
		</form>
	</div>
<?php endif ?>
