<?php
/**
 * @author <marcin.kurczewski@gammanet.pl> Marcin Kurczewski
 */
if (isset($this->response))
{
	$errors = false;

	foreach ($this->responses as $response)
	{
		if (isset($response['outputJSON']['message']))
		{
			if (is_array($response['outputJSON']['message']))
			{
				echo join('', array_map(function($str) { return '<p class="notice error">Błąd: ' . json_encode($str) . '</p>'; }, $response['outputJSON']['message']));
			}
			else
			{
				echo '<p class="notice error">Błąd: ' . $response['outputJSON']['message'] . '</p>';
			}
			$errors = true;
		}
		elseif ($response['outputStatusCode'] == 200 or $response['outputStatusCode'] == 201 or $response['outputStatusCode'] == 204)
		{
		}
		else
		{
			$errors = true;
		}
	}
	
	if (!$errors)
	{
		header('Location: ' . $this->url(array('controller' => 'training-centers', 'action' => 'index'), null, false));
		echo '<p class="notice">Ośrodek szkoleniowy dodany z sukcesem.</p>';
	}
	else
	{
		echo '<p class="notice error">Wystąpiły błędy podczas próby dodania ośrodka szkoleniowego.</p>';
	}
}
else
{
?>
<div class="op shaded">
	<ul class="op">
		<li class="icon-return"><a class="action-cancel action-return" href="<?php echo $this->url(array('controller' => 'training-centers', 'action' => 'index'), null, false); ?>">Powrót</a></li>
	</ul>
</div>

<form id="training-center-form" action="<?php echo $this->url(array('controller' => 'training-centers', 'action' => 'create'), null, true); ?>" method="post">

	<ul class="tab-switcher">
		<li>Dane podstawowe</li>
		<li>Opis ośrodka</li>
		<li>Zasoby</li>
		<li>Sale</li>
	</ul>

	<div class="tabs">

		<div class="tab">
			<fieldset>
				<div>
					<label for="edit-name">Nazwa ośrodka</label>
					<input id="edit-name" class="required name" name="name">
				</div>
				<div>
					<label for="edit-code">Kod ośrodka</label>
					<input id="edit-code" class="required code" name="code">
				</div>
				<div>
					<label for="edit-street">Ulica</label>
					<input id="edit-street" class="required street" name="street">
				</div>
				<div>
					<label for="edit-zip-code">Kod pocztowy</label>
					<input id="edit-zip-code" class="required zip-code" name="zip-code">
				</div>
				<div>
					<label for="edit-city">Miasto</label>
					<input id="edit-city" class="required city" name="city">
				</div>
				<div>
					<label for="edit-manager">Kierownik</label>
					<input id="edit-manager" class="person" name="manager">
				</div>
				<div>
					<label for="edit-phone-number">Telefon kontaktowy</label>
					<input id="edit-phone-number" class="phone-number" name="phone-number">
				</div>
				<div>
					<label for="edit-url">Strona internetowa</label>
					<input id="edit-url" class="url" name="url">
				</div>
			</fieldset>
		</div>

		<div class="tab">
			<textarea class="richtext" name="description"></textarea>
		</div>

		<div class="tab">
			<div id="resource-editor"></div>
		</div>

		<div class="tab">
			<div id="room-editor"></div>
		</div>

	</div>

	<div class="op">
		<button class="button default action-add" name="submit-action" type="submit" value="create">Utwórz</button>
		<button class="button action-cancel" name="submit-action" type="button" value="cancel" onclick="window.location.href='<?php echo $this->url(array('controller' => 'training-centers', 'action' => 'index'), null, true); ?>'; return false; ">Anuluj</button>
	</div>
	<input type="hidden" name="room-data">
	<input type="hidden" name="resource-data">
	<input type="hidden" name="resources-name-source" value="<?php
		$resourceTypes = array();
		foreach ($this->resourceTypes['outputJSON'] as $resourceType)
		{
			$resourceTypes []= $resourceType['name'];
		}
		echo htmlspecialchars(json_encode(array_unique($resourceTypes)));
	?>">
</form>

<?php
$this->headScript()->appendFile($this->baseUrl('js/entity-editor.js'));
}
?>
