	<div id="pageWrapper">
		<div id="test">
			<div id="adminTop">
                <h1><?php echo $this->translate('Konfiguracja gry'); ?></h1>
                <a href="<?php echo $this->baseUrl(); ?>/nauczyciel"><img src="<?php echo $this->baseUrl(); ?>/img/headmaster_logo.png" alt="<?php echo $this->translate('HeadMaster'); ?>" class="logo" width="287" height="48" /></a>
			</div>
			<div id="adminContent" class="clearfix">
                <div id="adminContent1" class="adminContentColumn fleft">
                    <h2><?php echo $this->translate('Poziom trudności'); ?></h2>

                    
                    <h2><?php echo $this->translate('Rodzaj szkoły'); ?></h2>
                    
                </div>
                <div id="adminContent1" class="adminContentColumn fleft">
                    
                </div>
                <div id="adminContent1" class="adminContentColumn fleft">
                    
                </div>
            </div>
		</div>
		<div id="unijna_stopka_space"></div>
	</div>
