	<div id="pageWrapper">
		<div id="loginHeader" class="clearfix">
			<a href="<?php echo $this->baseUrl(); ?>/nauczyciel"><img src="<?php echo $this->baseUrl(); ?>/img/headmaster_logo.png" alt="<?php echo $this->translate('HeadMaster'); ?>" class="logo" width="287" height="48" /></a>
		</div>
		<div id="login" class="clearfix">
			<div id="loginForm">
				<h2><?php echo $this->translate('Zbyt mało pytań w bazie danych.'); ?></h2>
				<a href="<?php echo $this->baseUrl('/'); ?>" class="goBack">&laquo; <?php echo $this->translate('Wróć'); ?></a>
			</div>
		</div>
		<div id="unijna_stopka_space"></div>
	</div>
