	<?php
		$cols = array(
			$this->translate('Sygnatura czasowa'),
			$this->translate('Nazwa użytkownika'),
			$this->translate('Treść pytania'),
			$this->translate('Odpowiedź 1'),
			$this->translate('Odpowiedź 2'),
			$this->translate('Odpowiedź 3'),
			$this->translate('Odpowiedź 4'),
			$this->translate('Odpowiedź 5'),
			$this->translate('Odpowiedź 6'),
			$this->translate('Która z powyższych propozycji opodwiedzi, jest odpowiedzią dobrą?'),
			$this->translate('Treść podpowiedzi (koło ratunkowe Expert)'),
			$this->translate('Rodzaj szkoły'),
			$this->translate('Do którego działu podstawy programowej można zakwalifikować pytanie?'),
			$this->translate('Jaka jest skala trudności pytania'),
            $this->translate('Rysunek')
		)
	?>
	<script type="text/javascript" src="<?php echo $this->baseUrl(); ?>/js/uploadify/swfobject.js"></script>
	<script type="text/javascript" src="<?php echo $this->baseUrl(); ?>/js/uploadify/jquery.uploadify.v2.1.4.min.js"></script>
	<div id="pageWrapper">
		<div id="test">
			<div id="adminTop">
                <h1>Import pytań z pliku csv</h1>
		        <?php $this->HeadmasterLogo(); ?>
		        <?php $this->BreadCrumbs(); ?>
		        <?php $this->AdminTabs($this->user->user_role,'administrator'); ?>			
			</div>
			<div id="adminContent" class="clearfix">

				<div id="error" class="adminContentColumn hidden">                                
					<h2><?php echo $this->translate('Wystąpił błąd podczas importu dokumentu'); ?></h2>
                    <p><?php echo $this->translate('Prawdopodobnie wskazany dokument posiada nieprawidłową lub niepełną strukturę by można było importować z niego pytania. Sprawdź w dokumentacji czy struktura Twojego pliku odpowiada podanej specyfikacji.'); ?></p>
                    <br />           
					<p><a href="<?php echo $this->baseUrl(); ?>/administrator/import-pytan"><img src="<?php echo $this->baseUrl(); ?>/img/famfam/arrow_refresh.png" alt="" style="margin: 0 10px 0 0;" /><?php echo $this->translate('Spróbuj jeszcze raz'); ?></a></p>
                </div>
                		
				<div id="step_1" class="adminContentColumn">
					<div id="step_1_content">                                
						<h2><?php echo $this->translate('Wybierz dokument, który chesz zaimportować do bazy danych:'); ?> (1/4)</h2>
						<p><?php echo $this->translate('Lista dokumentów w Google Docs:'); ?></p>
						<p>
							<select name="google_document" id="google_document">
								<option value=""> -- <?php echo $this->translate('Wybierz dokument'); ?> -- </option>
								<?php foreach($this->spreadsheets as $spreadsheet) {
									if($spreadsheet['key'] ==$this->google_docs_link) {
										$sel = ' SELECTED="SELECTED"';
									} else {
										$sel = '';
									}			
								?>
								<option value="<?php echo $spreadsheet['key']; ?>"<?php echo $sel; ?>><?php echo $spreadsheet['title']; ?></option>
								<?php } ?>
							</select>
                        </p>
                        <br />
						<p><?php echo $this->translate('Arkusze w wybranym dokumencie:'); ?></p>
                        <p>
							<select name="google_worksheet" id="google_worksheet">
								<?php foreach($this->worksheets as $worksheet) { ?>
								<option value="<?php echo $worksheet['id']; ?>"><?php echo $worksheet['title']; ?></option>
								<?php } ?>
							</select>
                        </p>
						<div id="s1d"></div>
						<img src="<?php echo $this->baseUrl(); ?>/img/up_dalej.png" id="step_1_dalej" class="step_dalej" alt="" />
					</div>
					<div id="step_1_preload" class="hidden">                                
						<h2><?php echo $this->translate('Proszę czekać'); ?> (1/4)</h2>
						<p><?php echo $this->translate('Trwa ładowanie dokumentu.'); ?></p>
						<p style="display:block;margin:30px 0;text-align:center;"><img src="<?php echo $this->baseUrl(); ?>/img/ajax-loader.gif" alt="Preload" /></p>
					</div>
                </div>			

				<div id="step_2" class="adminContentColumn hidden">                                
					<h2><?php echo $this->translate('Ustaw kolejność kolumn'); ?> (2/4)</h2>
					<table id="importQuestions" class="listaPytan">
						<thead>
							<th width="50%"><?php echo $this->translate('Interpretuj pole jako:'); ?></th>
							<th width="50%"><?php echo $this->translate('Treść z pierwszego rzędu'); ?></th>
						</thead>
						<tbody>
						</tbody>
					</table>
					<img src="<?php echo $this->baseUrl(); ?>/img/up_dalej.png" id="step_2_dalej" class="step_dalej" alt="" />
                </div>			

				<div id="step_3" class="adminContentColumn hidden">                                
					<h2><?php echo $this->translate('Opcje importu'); ?> (3/4)</h2>
					<p>
						<input type="checkbox" name="truncate" id="truncate" />
						<label for="truncate"><?php echo $this->translate('Wyczyść bazę danych przed dodaniem nowych pytań'); ?></label>
					</p>
					<p class="hidden">
						<input type="checkbox" name="ignoreFirst" id="ignoreFirst" />
						<label for="truncate"><?php echo $this->translate('Ignoruj pierwszą linie z pliku (jeżeli w pierwszej linii pojawiają się jedynie nazwy pól)'); ?></label>
					</p>
					<p>
						<img src="<?php echo $this->baseUrl(); ?>/img/up_dalej.png" id="step_3_dalej" class="step_dalej" alt="" />
					</p>
                </div>			

                <div id="step_4" class="adminContentColumn hidden">                                
					<h2><?php echo $this->translate('Trwa importowanie'); ?> <span id="step">0</span> <?php echo $this->translate('z'); ?> <span id="count">0</span> (4/4)</h2>
					<div id="wait">
						<div></div>
					</div>
					<p id="finished" class="hidden"><a href="<?php echo $this->baseUrl(); ?>/administrator">&laquo; <?php echo $this->translate('Wróć'); ?></a></p>
                </div>

            </div>
		</div>
		<div id="unijna_stopka_space"></div>
	</div>
	<script type="text/javascript">
	//<![CDATA[
	var categories = [<?php
	$s = '';
	foreach($cols as $c ) {
		echo $s,'"',$c,'"';
		$s = ',';
	}
	?>];
	function zapiszDoBazy(questions, step) {
		var count = 0;
		for(var i in questions) {
			count = count+1;
		}
        $.post('<?php echo $this->baseUrl(); ?>/administrator/import-pytan-zapisz-do-bazy/',
        {
            'question' : JSON.stringify(questions[step]),
            'document' : JSON.stringify($('#google_document').val())
        },
        function() {
            $('#count').html(count);
            var width = Math.floor((step/count)*920);
            var opacity = step/count; if(opacity<0.2) opacity = 0.2;
            var percent = Math.floor((step/count)*100);
            var percent_prev = Math.floor(((step-1)/count)*100); if(percent_prev<1) percent_prev = 1;                        
            if(percent > percent_prev) {
                if(width<20) width=20;
               	$('#wait div').css('width',width);                       	
               	$('#wait div').css('opacity',opacity);                       	
            }
            if((step+1)<count) {
                $('#step').html(step);
                zapiszDoBazy(questions, step+1);
            } else {                            
                $('#step').html(step+1);
               	$('#wait div').css('width','100%');                       	
               	$('#wait div').css('opacity',1);                       	
                $('#wait div').animate({
                	'backgroundColor': '#137600'
                },function(){
                	$('#finished').fadeIn();
                });
            }
        });    
	}

	// Krok 1 - upload pliku		
    $(document).ready(function() {
        var json;
        var pozycja = 0;
		$('table.listaPytan tbody tr').last().children('td').first().addClass('last_l');
        $('table.listaPytan tbody tr').last().children('td').last().addClass('last_r');
        $('#google_document').change(function(){
            $('#google_worksheet').html('');
            $.ajax({
                type: 'POST',
                url: '<?php echo $this->baseUrl(); ?>/administrator/arkusze',
                data: {'key': $('#google_document').val() },
                success: function(json){
                    for(var row in json) {
                        $('#google_worksheet').append('<option value="'+json[row].id+'">'+json[row].title+'</option>');
                    }
                },
                dataType: 'json' 
            });
        });
		$('#step_1_dalej').click(function(){
			$('#step_1_content').fadeOut(function(){
				$('#step_1_preload').fadeIn();
            });												
            $.ajax({
                type: 'POST',
                url: '<?php echo $this->baseUrl(); ?>/administrator/import-pytan-pobierz-pytania-google/',
                data: {'key': $('#google_document').val(), 'worksheet': $('#google_worksheet').val() },
                success: function(json){
                    $('#step_1').hide();
					if(json.validation) {
						var tableRows = '';
                        var tableRowClass = 'odd';
                        //var kolejnosc = [0,1,2,3,4,5,6,9,10,11,7,8,12,13];
						for(var i in json.file[0])
						{
							x = parseInt(i);
							z = x+1;
							tableRows = tableRows+'<tr class="'+tableRowClass+'"><td class="option"><select name="column[]" class="column_input" id="column_'+z+'_input">';
							tableRows = tableRows+'<option value="0">-- IGNORUJ --</option>';
							for(var j in categories) {
								if(json.kolejnosc[x] == j) {
									var selected = ' selected="selected"';
								} else {
									var selected = '';									
								}
								var J = parseInt(j)+1; 
								tableRows = tableRows+'<option value="'+J+'"'+selected+'>'+categories[j]+'</option>';		
							}							
							tableRows = tableRows+'</select></td><td class="fileContent">'+json.file[pozycja][x]+'</td></tr>';
							if(tableRowClass === 'odd') {
								tableRowClass = 'even';
							} else {
								tableRowClass = 'odd';
							}
							
						}
						$('table.listaPytan>tbody').append(tableRows);					
						$('#step_2').show();

                        // Krok 3 - konfiguracja
						$('#step_2_dalej').click(function(){
							$('#step_2').hide();
							$('#step_3').show();
							var selected = new Array();
							var columnsOrder = new Array();
							var y = 0;
							
							var alertString = '';							
							$('select.column_input').each(function(column){								
								columnsOrder[y] = $(this).val();
								alertString = alertString+'columnsOrder['+y+'] = '+$(this).val()+'\n';
								y =y+1;
							});
							var questions = new Array();
							$.each(json.file,function(key,val){
								var question_column = new Array();
								$.each(columnsOrder,function(col_k,col_v){
									if(col_v > 0)
									question_column[parseInt(col_v-1)] = val[parseInt(col_k)];
								});
								questions.push(question_column);
							}); 
							
							// Krok 4 - zapis do bazy wczytanych wcześniej pytań
							$('#step_3_dalej').click(function(){
								$('#step_3').hide();
								$('#step_4').show();
								var startFromStep = 0;
								if($("#ignoreFirst").is(":checked")) {
									startFromStep = 1;
								}
								if($("#truncate").is(":checked")) {
							        $.post('<?php echo $this->baseUrl(); ?>/administrator/ajax-truncate/',
							        {'truncate' : 1},
							        function(json) {
							        	zapiszDoBazy(questions, startFromStep);
							        }, 'json');    
								} else {
									zapiszDoBazy(questions, startFromStep);
								}
							});
						});		
					} else {
						// alert('Wystąpił błąd - ');
						$('#error').show();
					}
                },
            dataType: 'json' 
        });            
		});
	});
	//]]>
	</script>
