<div id="pageWrapper">
	<div id="test">
		<div id="adminTop">
			<h1><?php echo $this->translate('Lista pytań w bazie danych'); ?></h1>
	        <?php $this->HeadmasterLogo(); ?>
	        <?php $this->BreadCrumbs(); ?>
	        <?php $this->AdminTabs($this->user->user_role,'administrator'); ?>			
		</div>
		<div id="adminContent" class="clearfix">
			<div class="paginationTop">
			<?php
				echo $this->paginationControl($this->allQuestions, 'All', 'pagination.phtml');			
			?>
			</div>
			<div class="adminContentColumn">
				<table class="listaPytan">
					<thead>
						<tr>
							<th><?php echo $this->translate('ID'); ?></th>
							<th width="600" class="border"><?php echo $this->translate('Pytanie'); ?></th>
							<th><?php echo $this->translate('Odpowiedź'); ?></th>		
						</tr>						
					</thead>
					<tbody>				
					<?php
						$prevId = 0;
						$class = 'even';
						foreach($this->allQuestions as $key=>$question) {
							if($prevId != $question->id) {
								if($class == 'odd') {
									$class = 'even';
								} else {
									$class = 'odd';
								}
							}
					?>
						<tr class="<?php echo $class; ?>">
							<td><?php
								if($prevId != $question->id) {
									echo $question->id;
								}
							?></td>
							<td class="border"><?php
								if($prevId != $question->id) {
									echo $question->question;
								}
								$prevId = $question->id;
							?></td>
							<td<?php if($question->is_correct>0) echo ' class="correct"'; ?>><?php echo $question->answer; ?></td>
						</tr>
					<?php } ?>				
					</tbody>
				</table>				
			</div>
			<div class="paginationBottom">
			<?php
				echo $this->paginationControl($this->allQuestions, 'All', 'pagination.phtml');			
			?>
			</div>
		</div>
	</div>
	<div id="unijna_stopka_space"></div>
</div>
<script type="text/javascript">
//<![CDATA[
	$(document).ready(function() {
		$('table.listaPytan tbody tr').last().children('td').first().addClass('last_l');
		$('table.listaPytan tbody tr').last().children('td').last().addClass('last_r');
		$('a.ajax').click(function(){
			var link = $(this).attr("href");
			$('#tableBody').load(link+' #tableBody');
		});
		$('a.ajaxConfirm').click(function(){
			var link = $(this).attr("href");
			var confirmation = confirm('Czy jesteś pewien?');
			if(confirmation) {
				$('#tableBody').load(link+' #tableBody');
			} else {
				return false;
			}
		});
	});
//]]>
</script>
