<?php echo $this->partial('messages/tabs.phtml') ?>
<div class="table-area">
    <table>
        <tr>
            <th><?php echo $this->translate('message sender') ?></th>
            <th width="35%"><?php echo $this->translate('message subject') ?></th>
            <th width="15%"><?php echo $this->translate('message send date') ?></th>
        </tr>
        <tr>
            <td><?php echo $this->message->sender_username ?></td>
            <td><?php echo $this->message->subject ?></td>
            <td><?php echo $this->message->send_date ?></td>
        </tr>
        <tr>
            <td colspan="4">
                <?php echo nl2br($this->message->body) ?>
            </td>
        </tr>
    </table>
</div>