<?php
/**
 * @author <marcin.kurczewski@gammanet.pl> Marcin Kurczewski
 */
echo '<div class="op shaded">';
echo $this->paginator($this->pageNumber, $this->totalRecords, $this->recordsPerPage);
echo '<ul class="op">',
	'<li class="icon-create"><a href="' . $this->url(array('controller' => 'users', 'action' => 'create'), null, false) . '">Utwórz nowego użytkownika</a></li>',
	'</ul>';
echo '</div>';

if (isset($this->users['outputJSON']['message']))
{
	echo '<p class="notice error">Błąd: ' . $this->users['outputJSON']['message'] . '</p>';
}
else
{
?>
<table class="shaded">
	<thead>
		<tr>
			<th class="lp"><span>L.p.</span></th>
			<th><span>Imię i nazwisko</span></th>
			<th><span>Nazwa użytkownika</span></th>
			<th><span>Rola</span></th>
			<th><span>E-mail</span></th>
			<th class="op"><span>Dostępne operacje</span></th>
		</tr>
	</thead>
	<tbody>
	<?php
		$i = 1;
		foreach ($this->users['outputJSON'] as $user)
		{
	?>
		<tr>
			<td class="lp"><?php echo $i ++; ?></th>
			<td><a href="<?php echo $this->url(array('controller' => 'users', 'action' => 'view', 'id' => $user['id']), null, true); ?>"><?php echo $user['first_name'] . ' ' . $user['last_name']; ?></a></td>
			<td><?php echo $user['username']; ?></td>
			<td><?php echo $user['role']; ?></td>
			<td><?php echo $user['email']; ?></td>
			<td class="op">
				<ul class="op">
					<li class="icon-edit"><a href="<?php echo $this->url(array('controller' => 'users', 'action' => 'edit', 'id' => $user['id']), null, true); ?>">Edytuj</a></li>
					<li class="icon-delete"><a href="<?php echo $this->url(array('controller' => 'users', 'action' => 'delete', 'id' => $user['id']), null, true; ?>">Usuń</a></li>
				</ul>
			</td>
		</tr>
	<?php
		}
	?>
	</tbody>
</table>
<?php
}
?>
