	<div id="pageWrapper">
		<div id="loginHeader" class="clearfix">
			<a href="<?php echo $this->baseUrl('/'); ?>"><img src="<?php echo $this->baseUrl(); ?>/img/headmaster_logo.png" alt="<?php echo $this->translate('HeadMaster'); ?>" class="logo" width="287" height="48" /></a>
		</div>
		<div id="login" class="clearfix">
			<div id="loginForm">
				<h2 class="center" style="padding:0 20px;"><?php echo $this->translate('Do prawidłowego działania gra Headmaster wymaga włączonej obsługi JavaScript\'u.'); ?></h2>
			</div>
		</div>
		<div id="unijna_stopka_space"></div>
	</div>
	<script type="text/javascript">
    //<![CDATA[
	$(document).ready(function() {
		$("#gameStart").validationEngine('attach',{
			'autoHidePrompt': true
		});
	});
    //]]>		
	</script>
