	<div id="pageWrapper">
		<div id="loginHeader" class="clearfix">
			<a href="<?php echo $this->baseUrl('/'); ?>"><img src="<?php echo $this->baseUrl(); ?>/img/headmaster_logo.png" alt="<?php echo $this->translate('HeadMaster'); ?>" class="logo" width="287" height="48" /></a>
		</div>
		<div id="login" class="clearfix">
			<div id="loginForm">
				<h2 class="center" style="padding:0 20px;"><?php echo $this->translate('Posiadasz starą wersję przeglądarki internetowej. Aby zagrać w grę HeadMaster zaktualizuj przeglądarkę Internet Explorer conajmniej do wersji 8 lub zainstaluj którąś z poniższych:'); ?></h2>
				<p class="center"><a href="https://www.google.com/intl/pl/chrome/browser/" target="_blank"><?php echo $this->translate('Chrome'); ?></a></p>
				<p class="center"><a href="http://www.mozilla.org/pl/firefox/new/" target="_blank"><?php echo $this->translate('Firefox'); ?></a></p>
				<p class="center"><a href="http://www.opera.com/download/" target="_blank"><?php echo $this->translate('Opera'); ?></a></p>
			</div>
		</div>
		<div id="unijna_stopka_space"></div>
	</div>
	<script type="text/javascript">
    //<![CDATA[
	$(document).ready(function() {
		$("#gameStart").validationEngine('attach',{
			'autoHidePrompt': true
		});
	});
    //]]>		
	</script>
