Drop index "towar_indeks_key";
Drop index "system_obiekt_key2";
Drop index "system_action_key2";
Drop index "system_acl_grupa_ukey2";
Drop index "system_user_login2";
Drop index "messages_key";
Drop index "grupy_towarow_key";
Drop index "koszyk_key";


Create index "towar_indeks_key" on "towar" using btree ("to_indeks","to_ean","to_ws");
Create index "towar_producent_key" on "towar" using btree ("to_pr_id");
Create unique index "towar_u_indeks_key" on "towar" using btree ("to_indeks");
Create index "towar_parametry_fk" on "towar_parametry" using btree ("tp_to_id");
Create index "kategoria_parent_key" on "kategorie" using btree ("ka_parent");
Create index "towar_sklep_key" on "towar_sklep" using btree ("ts_to_id","ts_sk_id");
Create index "stany_magazynowe_key" on "stany_magazynowe" using btree ("sm_to_id","sm_ma_id");
Create index "kontrahent_sklep_key" on "kontrahent_sklep" using btree ("ks_sk_id","ks_su_id");
Create index "rabat_kontrahenta_key" on "rabat_kontrahenta" using btree ("rk_ka_id","rk_ks_id");
Create index "rabat_ilosciowy_key" on "rabat_ilosciowy" using btree ("ri_sk_id","ri_ka_id");
Create index "system_obiekt_key2" on "system_obiekt" using btree ("so_server","so_klucz");
Create index "system_acl_obiekt_key" on "system_acl_obiekt" using btree ("sao_grupa_id","sao_server","sao_klucz");
Create index "system_action_key2" on "system_action" using btree ("sa_server","sa_page_id","sa_action");
Create index "system_log_key" on "system_log" using btree ("sl_user_id","sl_server","sl_tin","sl_tout");
Create unique index "system_acl_grupa_ukey2" on "system_acl_grupa" using btree ("sag_grupa_id","sag_user_id","sag_server");
Create index "system_user_login2" on "system_user" using btree ("su_login","su_pesel");
Create index "update_db_key" on "system_update" using btree ("su_klucz","su_data");
Create index "system_action_log_key" on "system_action_log" using btree ("sal_user_id","sal_action","sal_data");
Create index "koszyk_key" on "koszyk" using btree ("ko_su_id","ko_ts_id","ko_deadline","ko_rez_data");
Create index "zamowienia_key" on "zamowienia" using btree ("za_su_id","za_sk_id","za_data");
Create index "zampoz_key" on "zampoz" using btree ("zp_za_id","zp_ts_id");
Create index "messages_key" on "messages" using btree ("msg_label","msg_lang");
Create index "towar_kategoria_key" on "towar_kategoria" using btree ("tk_to_id","tk_ka_id");
Create index "nieudane_zakupy_key" on "nieudane_zakupy" using btree ("nz_ts_id","nz_su_id");
Create index "ulubione_key" on "ulubione" using btree ("ul_su_id","ul_to_id");
Create index "ruchy_key" on "ruchy" using btree ("ru_su_id","ru_ts_id","ru_ma_id");
Create index "grupy_towarow_key" on "grupy_towarow" using btree ("gt_to_id1","gt_to_id2","gt_grupa");
Create index "towar_opcje_key" on "opcje_towaru" using btree ("ot_to_id");
Create index "promocja_towaru_key" on "promocja_towaru" using btree ("pt_ts_id","pt_pm_id");
Create index "zapytania_key" on "zapytania" using btree ("za_ts_id","za_odp_su_id");
