<p><?php echo $this->translate('An error occured. Try checking following:') ?></p>
<ul>
	<li><?php echo $this->translate('Did you grant access to required Google services?') ?></p>
	<li><?php echo $this->translate('Are you domain administrator?') ?></p>
	<li><?php echo $this->translate('Does your domain have provisioning API enabled?') ?></p>
	<li><?php echo $this->translate('Did you erase browser cache?') ?></p>
</ul>

