<div class="edu-content">
    <h1>Bank centralny</h1>

    <p>Instytucja odpowiedzialna za funkcjonowanie systemu bankowego. Zazwyczaj działa jako jednostka państwowa, bądź
       podporządkowana państwu. W Polsce funkcję banku centralnego pełni Narodowy Bank Polski.</p>

    <h1>Funkcje banku centralnego</h1>
    <ul>
        <li>Bank centralny emituje pieniądz gotówkowy. Następnie wprowadza go do obiegu poprzez skup metali
            szlachetnych, walut obcych oraz w formie długu, czyli udzielając kredytów bankom komercyjnym (w niektórych
            państwach również rządowi). Jest jedyną instytucją uprawnioną do emitowania znaków pieniężnych w danym
            państwie.
        </li>
        <li>Bank centralny jest bankiem rozliczeniowym banków komercyjnych i innych instytucji finansowych. Każdy bank
            komercyjny posiada w banku centralnym rachunek, na którym rejestruje rozliczenia z innymi bankami. Bank
            centralny świadczy usługi bankowe innym bankom (przyjmuje depozyty po tzw. stopie depozytowej oraz udziela
            im kredytów). Bank centralny realizuje również transakcje z zagranicznymi bankami centralnymi i instytucjami
            międzynarodowymi.
        </li>
        <li>Bank centralny jest bankiem skarbu państwa. Prowadzi rachunki instytucji państwowych. Utrzymuje rachunki
            depozytowe państwa, prowadzi kasową obsługę budżetu, obsługuje dług publiczny. W wyjątkowych przypadkach
            bank centralny może udzielić państwu kredytu (w formie kredytu bezpośredniego lub zakupu skarbowych papierów
            wartościowych). Jednak z racji na zagrożenie inflacją, do której mogą doprowadzić tego typu transakcje, jest
            to obecnie bardzo rzadko stosowane rozwiązanie
        </li>
    </ul>

    <h1>Funkcje stabilizująco-kontrolne</h1>
    <ul>
        <li>Bank centralny formułuje cele polityki pieniężnej państwa i steruje nią za pomocą dostępnych instrumentów.
        </li>
        <li>Bank centralny utrzymuje i zarządza rezerwami dewizowymi kraju, a także prowadzi politykę kształtowania
            kursu waluty krajowej.
        </li>
        <li>Bank centralny nadzoruje działalność banków komercyjnych, dbając o bezpieczeństwo systemu bankowego.</li>
        <li>Bank centralny reguluje podaż pieniądza w obiegu (poprzez np. operacje otwartego rynku i ustalanie stóp
            procentowych) i oddziałuje na politykę kredytową banków komercyjnych.
        </li>
    </ul>

    <h1>Kontrola udzielanych kredytów i stóp procentowych</h1>

    <p>Zadaniem kontroli wysokości udzielanych przez banki komercyjne kredytów jest utrzymanie podaży pieniądza na
       określonym poziomie w celu przywrócenia lub po prostu zapewnienia równowagi w gospodarce i/lub obrotach bieżących
       z zagranicą. Kontrola kredytów może przybierać różne formy. Różny też może być zakres jej stosowania. Może
       przybrać bowiem formę:</p>
    <ul>
        <li>kontyngentów lub pułapów kredytowych,</li>
        <li>kwotowych lub procentowych ograniczeń dotyczących depozytów lub papierów wartościowych,</li>
        <li>dyrektywnych wskaźników określających procentowy stosunek danego typu kredytów do kapitału własnego,</li>
        <li>badania wypłacalności banków komercyjnych,</li>
        <li>innych łagodniejszych form kontroli.</li>
    </ul>
    <p>Kontrola poziomu stóp procentowych natomiast, należy do bezpośrednich instrumentów selektywnego oddziaływania na
       gospodarkę za pomocą zjawisk pieniężnych. Prowadzi się ją poprzez podmiotowe lub przedmiotowe różnicowanie stawek
       oprocentowania bądź za pomocą wyznaczania górnej lub dolnej wysokości stóp procentowych bądź też narzucania
       bankom komercyjnym ściśle określonej wysokości stawek.</p>

    <h1>Polityka rezerw obowiązkowych</h1>

    <p>Polityka rezerw obowiązkowych zalicza się do instrumentów ilościowych. Stopa rezerw obowiązkowych określa, ile
       procent od każdego złotego (PLN) zdeponowanego na rachunkach a vista lub terminowych banki komercyjne muszą
       przekazać na swój rachunek w banku centralnym lub utrzymywać je w swojej kasie w formie zapasów gotówki. Rezerwie
       obowiązkowej przypisuje się rolę rynkowego instrumentu ogólnego oddziaływania, gdyż stopy ich ustalane są
       zazwyczaj w jednakowej wysokości dla wszystkich banków, a obowiązek ich tworzenia nie łączy się z ingerencją w
       układ stosunków między bankami komercyjnymi i klientami. Istnieją różne zasady odprowadzania tych rezerw na
       rachunek w banku centralnym. Zależą one głównie od metody naliczania rezerw, wysokości stopy, oprocentowania
       środków utrzymywanych w formie rezerw jak również i gromadzenia środków.</p>

    <h1>Instrumenty bezpośrednie oddziaływania na rynek pieniężny</h1>

    <p>Stosowane przez bank centralny instrumenty bezpośredniego oddziaływania można podzielić na dwie zasadnicze grupy.
       Pierwsza obejmuje instrumenty wykorzystywane do kontroli rozmiarów udzielanych kredytów i wysokości stóp
       procentowych, druga zaś swoistego rodzaju oddziaływanie poprzez perswazję.</p>

    <hr/>

    <h2>Która z poniższych funkcji nie należy do funkcji Banku Centralnego?</h2>

    <form method="POST" action="<?php echo $this->url(array('action'     => 'index',
                                                            'controller' => 'map'
                                                      ), null, true
    ) ?>">
        <input type="radio" id="1a" name="answer"/>
        <label for="1a">regulacja podaży pieniądza</label>
        <br/>
        <input type="radio" id="1b" name="answer"/>
        <label for="1b">prowadzenie rachunków instytucji państwowych</label>
        <br/>
        <input type="radio" id="1c" name="answer"/>
        <label for="1c">regulowanie rynku papierów wartościowych</label>
        <br/>
        <input type="radio" id="1d" name="answer"/>
        <label for="1d">zarządzanie rezerwami dewizowymi kraju</label>
        <br/>
        <input type="submit" class="btn-orange" value="Wyślij"/>
    </form>
</div>
