<?php
	echo $this->doctype();
	$controller = Zend_Controller_Front::getInstance();
	$controllerName = $controller->getRequest()->getControllerName();
	$actionName = $controller->getRequest()->getActionName();
	//trigger_error('Layout - ' . $controllerName . ' ' . $actionName, E_USER_WARNING);
?>
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
	<title><?php echo $this->translate('application_title'); ?></title>
	<?php
		$this->headLink()->appendStylesheet($this->baseUrl('css/bootstrap.min.css'));
		$this->headLink()->appendStylesheet($this->baseUrl('css/jquery-ui.css'));
		$this->headLink()->appendStylesheet($this->baseUrl('css/style.css'));
		if (file_exists($file = 'css/' . $controllerName . '/base.css'))
		{
			$this->headLink()->appendStylesheet($this->baseUrl($file));
		}
		if (file_exists($file = 'css/' . $controllerName . '/' . $actionName . '.css'))
		{
			$this->headLink()->appendStylesheet($this->baseUrl($file));
		}
		$this->headScript()->appendFile($this->baseUrl('js/utils.js'));
		if (file_exists($file = 'js/' . $controllerName . '/base.js'))
		{
			$this->headScript()->appendFile($this->baseUrl($file));
		}
		if (file_exists($file = 'js/' . $controllerName . '/' . $actionName . '.js'))
		{
			$this->headScript()->appendFile($this->baseUrl($file));
		}
		echo $this->headMeta();
		echo $this->headLink();
		echo $this->jQuery();
		echo $this->headScript();

		$session = new Zend_Session_Namespace('language');
	?>
	<link href="<?php echo $this->baseUrl('/img/favicon.ico'); ?>" type="image/ico" rel="shortcut icon" />
</head>
<body id="<?php echo "$controllerName-$actionName" ?>">
	<div id="top">
		<a class="logo logo_<?php echo $session->language; ?>" href="<?php echo $this->url(array('controller' => 'dashboard', 'action' => 'index'), null, true) ?>"><?php echo $this->translate('application_title'); ?></a>
		<?php if ($this->user): ?>
			<div class="username">
				<span class="username-popup-toggle"><a><?php echo $this->user->email ?></a></span>
				<div class="username-popup">
					<p class="name"><?php echo $this->user->name ?></p>
					<p class="email"><?php echo $this->user->email ?></p>
					<?php echo $this->languageSelect() ?>
					<br>
					<a href="<?php echo $this->url(array('action' => 'logout', 'controller' => 'auth'), null, true) ?>"><?php echo $this->translate('auth_logout_button') ?></a>
				</div>
			</div>
			<script type="text/javascript">
				$('.username-popup-toggle').click(function() {
					$('.username-popup').toggle();
				});
			</script>
		<?php else: ?>
			<div class="username">
				<!--<?php echo $this->translate('auth_not_logged_in_text') ?>-->
				<?php echo $this->languageSelect() ?>
			</div>
		<?php endif ?>
		<div class="clean"></div>
	</div>
	<div id="content">
	    <?php if (isset($this->messenger) and (($controllerName != 'dashboard') or ($actionName != 'index')) and ($controllerName != 'error')): ?>
			<?php echo $this->messenger->render(); ?>
		<?php endif ?>
		<?php if (!$this->user): ?>
			<div id="slogan">
				<?php echo $this->translate('welcome_text'); ?>
			</div>
			<div class="login">
				<ul class="advpoints" id="login_advpoints">
					<li class="advpoints_green"><span><?php echo $this->translate('welcome_text_1'); ?></span></li>
					<li class="advpoints_blue"><span><?php echo $this->translate('welcome_text_2'); ?></span></li>
					<li class="advpoints_red"><span><?php echo $this->translate('welcome_text_3'); ?></span></li>
					<li class="advpoints_yellow"><span><?php echo $this->translate('welcome_text_4'); ?></span></li>
				</ul>
				<div class="balloon">
					<h1><?php echo $this->translate('application_title') ?></h1>
					<p><?php echo $this->translate('auth_login_text') ?></p>
					<a class="btn btn-primary" href="<?php echo $this->url(array('action' => 'open-id', 'controller' => 'auth'), null, true) ?>">
						<?php echo $this->translate('auth_login_button') ?>
					</a>
				</div>
			</div>
		<?php endif ?>
		<?php echo $this->layout()->content ?>
	</div>
	<div id="throbber">
		<div id="throbber-whole">
			<div id="throbber-text"><?php echo $this->translate('misc_progress_text') ?></div>
			<div id="throbber-img">
				<img src="<?php echo $this->baseUrl('/img/kolko_2.gif'); ?>" alt="<?php echo $this->translate('misc_progress_text') ?>">
			</div>
		</div>
	</div>
	<div id="footer">
		<?php echo $this->translate('copyright_text_prefix') ?>
		<a target="_blank" href="http://gammanet.pl/school-agent"><?php echo $this->translate('copyright_text_link'); ?></a>
		<?php echo $this->translate('copyright_text_suffix') ?>
	</div>
</body>
</html>
