<a href="javascript:window.history.back()" id="go-back">wróć</a>
<?php if (!empty($this->my_courses)): ?>
<h1>Twoje szkolenia</h1>
<table class="results" cellspacing="0" cellpadding="0">
    <tr>
        <th></th>
        <th>szkolenie</th>
        <th>ośrodek</th>
        <th>termin</th>
        <th>cena</th>
        <th>status</th>
        <th>szczegóły</th>
    </tr>
    <?php foreach ($this->my_courses as $i => $item): ?>
        <tr class="<?php echo $i % 2 ? 'odd' : 'even' ?>">
            <td class="text-center"><?php if ($item->color): ?><div class="color-box" style="background-color: <?php echo $item->color ?>">&nbsp;</div><?php endif ?></td>
            <td><a href="<?php echo $this->makeUrl('view', 'www', array('courseID' => $item->id)) ?>"><?php echo $item->course_name ?></a><div class="hint"><?php echo $item->code ?></div></td>
            <td><?php echo $item->tc_name ?><div class="hint"><?php echo $item->city ?></div></td>
            <td><?php echo $this->formatDate($item->start_date) ?><br/><?php echo $this->formatDate($item->end_date) ?></td>
            <td><?php if ($item->price) echo $this->currency($item->price) ?></td>
            <td><?php echo $this->courseGroupStatus($item->status) ?></td>
            <td><a class="view" href="<?php echo $this->makeUrl('view', 'www', array('courseID' => $item->id)) ?>" title="Pokaż"></a></td>
        </tr>
    <?php endforeach ?>
</table>
<?php endif ?>