<?php if (isset($this->groups)): ?>
	<?php if ($this->groups->count() == 0): ?>
		<p><?php echo $this->translate('No groups found. Cannot create exam.') ?></p>
	<?php else: ?>
		<form action="<?php echo $this->url(array('controller' => 'exams', 'action' => 'resend', 'exam-id' => $this->exam->id), null, true) ?>" method="post">
			<fieldset>
				<label for="groups"><?php echo $this->translate('Groups') ?></label>
				<table class="pretty" id="gruops">
					<thead>
						<tr>
							<th><input type="checkbox"></th>
							<th class="ord"><?php echo $this->translate('#') ?></th>
							<th><?php echo $this->translate('Group name') ?></th>
							<th><?php echo $this->translate('Group e-mail') ?></th>
						</tr>
					</thead>
					<tbody>
						<?php $i = 1; foreach ($this->groups as $group): ?>
						<tr>
							<td><input type="checkbox" name="group[]" value="<?php echo $group->id ?>"></td>
							<td class="ord"><?php echo $i ++ ?></td>
							<td><?php echo $group->name ?></td>
							<td><?php echo $group->email ?></td>
						</tr>
						<?php endforeach ?>
					</tbody>
				</table>


				<label for="send-mail-container" class="for-button"></label>
				<div id="send-mail-container">
					<label for="send-mail">
						<input type="checkbox" name="send-mail" id="send-mail">
						<?php echo $this->translate('Send mail to participating groups') ?>
					</label>
				</div>

				<label for="submit" class="for-button"><?php echo $this->translate('Action') ?></label>
				<button type="submit" id="submit" class="btn btn-primary"><?php echo $this->translate('Resend') ?></button>

			</fieldset>
		</form>
	<?php endif ?>
<?php endif ?>
